vlib work
vlib activehdl

vlib activehdl/xil_defaultlib
vlib activehdl/xpm
vlib activehdl/axi_infrastructure_v1_1_0
vlib activehdl/xil_common_vip_v1_0_0
vlib activehdl/smartconnect_v1_0
vlib activehdl/axi_protocol_checker_v1_1_14
vlib activehdl/axi_vip_v1_0_2
vlib activehdl/axi_vip_v1_0_1
vlib activehdl/lib_cdc_v1_0_2
vlib activehdl/proc_sys_reset_v5_0_11
vlib activehdl/xlconstant_v1_1_3
vlib activehdl/axi_lite_ipif_v3_0_4
vlib activehdl/lib_pkg_v1_0_2
vlib activehdl/axi_timer_v2_0_15
vlib activehdl/generic_baseblocks_v2_1_0
vlib activehdl/axi_register_slice_v2_1_13
vlib activehdl/fifo_generator_v13_1_4
vlib activehdl/axi_data_fifo_v2_1_12
vlib activehdl/axi_crossbar_v2_1_14
vlib activehdl/axi_protocol_converter_v2_1_13

vmap xil_defaultlib activehdl/xil_defaultlib
vmap xpm activehdl/xpm
vmap axi_infrastructure_v1_1_0 activehdl/axi_infrastructure_v1_1_0
vmap xil_common_vip_v1_0_0 activehdl/xil_common_vip_v1_0_0
vmap smartconnect_v1_0 activehdl/smartconnect_v1_0
vmap axi_protocol_checker_v1_1_14 activehdl/axi_protocol_checker_v1_1_14
vmap axi_vip_v1_0_2 activehdl/axi_vip_v1_0_2
vmap axi_vip_v1_0_1 activehdl/axi_vip_v1_0_1
vmap lib_cdc_v1_0_2 activehdl/lib_cdc_v1_0_2
vmap proc_sys_reset_v5_0_11 activehdl/proc_sys_reset_v5_0_11
vmap xlconstant_v1_1_3 activehdl/xlconstant_v1_1_3
vmap axi_lite_ipif_v3_0_4 activehdl/axi_lite_ipif_v3_0_4
vmap lib_pkg_v1_0_2 activehdl/lib_pkg_v1_0_2
vmap axi_timer_v2_0_15 activehdl/axi_timer_v2_0_15
vmap generic_baseblocks_v2_1_0 activehdl/generic_baseblocks_v2_1_0
vmap axi_register_slice_v2_1_13 activehdl/axi_register_slice_v2_1_13
vmap fifo_generator_v13_1_4 activehdl/fifo_generator_v13_1_4
vmap axi_data_fifo_v2_1_12 activehdl/axi_data_fifo_v2_1_12
vmap axi_crossbar_v2_1_14 activehdl/axi_crossbar_v2_1_14
vmap axi_protocol_converter_v2_1_13 activehdl/axi_protocol_converter_v2_1_13

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"D:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"D:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"D:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93 \
"D:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/hdl/accelerator_bd.v" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work xil_common_vip_v1_0_0  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl/xil_common_vip_v1_0_vl_rfs.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v1_1_14  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/a1b2/hdl/axi_protocol_checker_v1_1_vl_rfs.sv" \

vlog -work axi_vip_v1_0_2  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl/axi_vip_v1_0_vl_rfs.sv" \

vlog -work axi_vip_v1_0_1  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_processing_system7_0_1/sim/accelerator_bd_processing_system7_0_1.v" \

vcom -work lib_cdc_v1_0_2 -93 \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_11 -93 \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/5db7/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/accelerator_bd/ip/accelerator_bd_rst_ps7_0_100M_1/sim/accelerator_bd_rst_ps7_0_100M_1.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/bd_0/hdl/bd_67a5.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/e870/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/bd_0/ip/ip_5/sim/bd_67a5_s00a2s_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/224a/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/bd_0/ip/ip_11/sim/bd_67a5_m00s2a_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/986a/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/bd_0/ip/ip_12/sim/bd_67a5_m00e_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/bd_0/ip/ip_6/sim/bd_67a5_sarn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/bd_0/ip/ip_7/sim/bd_67a5_srn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/bd_0/ip/ip_8/sim/bd_67a5_sawn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/bd_0/ip/ip_9/sim/bd_67a5_swn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/bd_0/ip/ip_10/sim/bd_67a5_sbn_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/5300/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/bd_0/ip/ip_2/sim/bd_67a5_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/cbcb/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/bd_0/ip/ip_3/sim/bd_67a5_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/cc66/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/bd_0/ip/ip_4/sim/bd_67a5_s00sic_0.sv" \

vlog -work xlconstant_v1_1_3  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/45df/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/bd_0/ip/ip_0/sim/bd_67a5_one_0.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/bd_0/ip/ip_1/sim/bd_67a5_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_0/sim/accelerator_bd_axi_smc_0.v" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/bd_0/hdl/bd_9e52.v" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/bd_0/ip/ip_5/sim/bd_9e52_s00a2s_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/bd_0/ip/ip_11/sim/bd_9e52_m00s2a_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/bd_0/ip/ip_12/sim/bd_9e52_m00e_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/bd_0/ip/ip_6/sim/bd_9e52_sarn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/bd_0/ip/ip_7/sim/bd_9e52_srn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/bd_0/ip/ip_8/sim/bd_9e52_sawn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/bd_0/ip/ip_9/sim/bd_9e52_swn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/bd_0/ip/ip_10/sim/bd_9e52_sbn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/bd_0/ip/ip_2/sim/bd_9e52_s00mmu_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/bd_0/ip/ip_3/sim/bd_9e52_s00tr_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/bd_0/ip/ip_4/sim/bd_9e52_s00sic_0.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/bd_0/ip/ip_0/sim/bd_9e52_one_0.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/bd_0/ip/ip_1/sim/bd_9e52_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_1_0/sim/accelerator_bd_axi_smc_1_0.v" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/bd_0/hdl/bd_9ea2.v" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/bd_0/ip/ip_5/sim/bd_9ea2_s00a2s_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/bd_0/ip/ip_11/sim/bd_9ea2_m00s2a_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/bd_0/ip/ip_12/sim/bd_9ea2_m00e_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/bd_0/ip/ip_6/sim/bd_9ea2_sarn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/bd_0/ip/ip_7/sim/bd_9ea2_srn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/bd_0/ip/ip_8/sim/bd_9ea2_sawn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/bd_0/ip/ip_9/sim/bd_9ea2_swn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/bd_0/ip/ip_10/sim/bd_9ea2_sbn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/bd_0/ip/ip_2/sim/bd_9ea2_s00mmu_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/bd_0/ip/ip_3/sim/bd_9ea2_s00tr_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/bd_0/ip/ip_4/sim/bd_9ea2_s00sic_0.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/bd_0/ip/ip_0/sim/bd_9ea2_one_0.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/bd_0/ip/ip_1/sim/bd_9ea2_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_0/sim/accelerator_bd_axi_smc_2_0.v" \

vcom -work axi_lite_ipif_v3_0_4 -93 \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/0ba0/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work lib_pkg_v1_0_2 -93 \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/832a/hdl/lib_pkg_v1_0_rfs.vhd" \

vcom -work axi_timer_v2_0_15 -93 \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/a004/hdl/axi_timer_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_timer_0_1/sim/accelerator_bd_axi_timer_0_1.vhd" \

vlog -work generic_baseblocks_v2_1_0  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f9c1/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_13  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/55c0/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work fifo_generator_v13_1_4  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/ebc2/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_1_4 -93 \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.vhd" \

vlog -work fifo_generator_v13_1_4  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.v" \

vlog -work axi_data_fifo_v2_1_12  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/95b9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_14  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f582/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_xbar_0/sim/accelerator_bd_xbar_0.v" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/bd_0/hdl/bd_5e63.v" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/bd_0/ip/ip_5/sim/bd_5e63_s00a2s_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/bd_0/ip/ip_11/sim/bd_5e63_m00s2a_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/bd_0/ip/ip_12/sim/bd_5e63_m00e_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/bd_0/ip/ip_6/sim/bd_5e63_sarn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/bd_0/ip/ip_7/sim/bd_5e63_srn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/bd_0/ip/ip_8/sim/bd_5e63_sawn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/bd_0/ip/ip_9/sim/bd_5e63_swn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/bd_0/ip/ip_10/sim/bd_5e63_sbn_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/bd_0/ip/ip_2/sim/bd_5e63_s00mmu_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/bd_0/ip/ip_3/sim/bd_5e63_s00tr_0.sv" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/bd_0/ip/ip_4/sim/bd_5e63_s00sic_0.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/bd_0/ip/ip_0/sim/bd_5e63_one_0.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/bd_0/ip/ip_1/sim/bd_5e63_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_axi_smc_2_1/sim/accelerator_bd_axi_smc_2_1.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/avgpool.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/conv1_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/conv1_p_weight_tecud.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/conv_last.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/fc.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/MUL_DP.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_biasb4t.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_biasdiF.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_buffbEo.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_buffbFp.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_buffcSB.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_buffcTB.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_buffdIJ.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_buffdJJ.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_convAem.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_convBew.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_convdXL.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_convEe0.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_CTL_s_axi.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_DATA_BIAS_m_axi.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_DATA_INPUT_OUTPUT_m_axi.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_DATA_OTHER_WEIGHTS_m_axi.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_fc_bCeG.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_featb3s.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_featdhF.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_featdVL.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_imagDeQ.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_mul_bkb.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_mul_d8N.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_mul_d9N.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_mux_pcA.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_mux_qcK.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_mux_sc4.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_mux_udo.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_mux_yd2.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_mux_zec.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_p3X3_1X1_WEIGHTS_m_axi.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_Shufb5t.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_ShufdjF.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_shufdWL.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_ShufRg6.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_uremd6N.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_uremd7N.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_uremocq.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_uremrcU.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_uremtde.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_uremvdy.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_uremwdI.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_uremxdS.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_weigbDo.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_weigcRA.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_weigctx.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_weigdHJ.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/ShuffleNetV2_weigdvH.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/shuffle_24_l_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/shuffle_24_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/shuffle_24_r_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/shuffle_48_l_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/shuffle_48_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/shuffle_48_r_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/shuffle_96_l_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/shuffle_96_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/shuffle_96_r_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_1x1_16p_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_1x1_16_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_1x1_32_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_1x1_4_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_1x1_8p_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_1x1_8_p.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_3x3_16_no_re.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_3x3_16_strid.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_3x3_16_strid_1.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_3x3_32_strid.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_3x3_32_strid_1.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_3x3_4_no_rel.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_3x3_8_no_rel.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_3x3_8_stride.v" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/9365/hdl/verilog/subconv_3x3_8_stride_1.v" \
"../../../bd/accelerator_bd/ip/accelerator_bd_ShuffleNetV2_0_1/sim/accelerator_bd_ShuffleNetV2_0_1.v" \

vlog -work axi_protocol_converter_v2_1_13  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f0ae/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/7e3a/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/2ad9/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/39ca/hdl/verilog" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/6eb1/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/1d61/hdl" "+incdir+../../../../accelerator_demo.srcs/sources_1/bd/accelerator_bd/ipshared/f80f/hdl/verilog" \
"../../../bd/accelerator_bd/ip/accelerator_bd_auto_pc_0/sim/accelerator_bd_auto_pc_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

