// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<26> conv1::ap_ST_fsm_state1 = "1";
const sc_lv<26> conv1::ap_ST_fsm_state2 = "10";
const sc_lv<26> conv1::ap_ST_fsm_state3 = "100";
const sc_lv<26> conv1::ap_ST_fsm_state4 = "1000";
const sc_lv<26> conv1::ap_ST_fsm_state5 = "10000";
const sc_lv<26> conv1::ap_ST_fsm_state6 = "100000";
const sc_lv<26> conv1::ap_ST_fsm_state7 = "1000000";
const sc_lv<26> conv1::ap_ST_fsm_state8 = "10000000";
const sc_lv<26> conv1::ap_ST_fsm_state9 = "100000000";
const sc_lv<26> conv1::ap_ST_fsm_state10 = "1000000000";
const sc_lv<26> conv1::ap_ST_fsm_state11 = "10000000000";
const sc_lv<26> conv1::ap_ST_fsm_state12 = "100000000000";
const sc_lv<26> conv1::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<26> conv1::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<26> conv1::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<26> conv1::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<26> conv1::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<26> conv1::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<26> conv1::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<26> conv1::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<26> conv1::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<26> conv1::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<26> conv1::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<26> conv1::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<26> conv1::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<26> conv1::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<32> conv1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv1::ap_const_lv32_1 = "1";
const sc_lv<1> conv1::ap_const_lv1_0 = "0";
const sc_lv<32> conv1::ap_const_lv32_2 = "10";
const sc_lv<32> conv1::ap_const_lv32_3 = "11";
const sc_lv<32> conv1::ap_const_lv32_4 = "100";
const sc_lv<1> conv1::ap_const_lv1_1 = "1";
const sc_lv<32> conv1::ap_const_lv32_5 = "101";
const sc_lv<32> conv1::ap_const_lv32_6 = "110";
const sc_lv<32> conv1::ap_const_lv32_7 = "111";
const sc_lv<32> conv1::ap_const_lv32_8 = "1000";
const sc_lv<32> conv1::ap_const_lv32_C = "1100";
const sc_lv<32> conv1::ap_const_lv32_11 = "10001";
const sc_lv<32> conv1::ap_const_lv32_12 = "10010";
const sc_lv<32> conv1::ap_const_lv32_17 = "10111";
const sc_lv<32> conv1::ap_const_lv32_18 = "11000";
const sc_lv<5> conv1::ap_const_lv5_0 = "00000";
const sc_lv<6> conv1::ap_const_lv6_0 = "000000";
const sc_lv<32> conv1::ap_const_lv32_19 = "11001";
const sc_lv<2> conv1::ap_const_lv2_0 = "00";
const sc_lv<32> conv1::ap_const_lv32_D = "1101";
const sc_lv<32> conv1::ap_const_lv32_13 = "10011";
const sc_lv<32> conv1::ap_const_lv32_9 = "1001";
const sc_lv<5> conv1::ap_const_lv5_18 = "11000";
const sc_lv<5> conv1::ap_const_lv5_1 = "1";
const sc_lv<6> conv1::ap_const_lv6_20 = "100000";
const sc_lv<6> conv1::ap_const_lv6_1 = "1";
const sc_lv<2> conv1::ap_const_lv2_3 = "11";
const sc_lv<2> conv1::ap_const_lv2_1 = "1";
const sc_lv<3> conv1::ap_const_lv3_0 = "000";
const sc_lv<32> conv1::ap_const_lv32_1E = "11110";
const sc_lv<8> conv1::ap_const_lv8_FF = "11111111";
const sc_lv<23> conv1::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<5> conv1::ap_const_lv5_2 = "10";
const bool conv1::ap_const_boolean_1 = true;

conv1::conv1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    ShuffleNetV2_faddbkb_U1 = new ShuffleNetV2_faddbkb<1,5,32,32,32>("ShuffleNetV2_faddbkb_U1");
    ShuffleNetV2_faddbkb_U1->clk(ap_clk);
    ShuffleNetV2_faddbkb_U1->reset(ap_rst);
    ShuffleNetV2_faddbkb_U1->din0(grp_fu_219_p0);
    ShuffleNetV2_faddbkb_U1->din1(grp_fu_219_p1);
    ShuffleNetV2_faddbkb_U1->ce(ap_var_for_const0);
    ShuffleNetV2_faddbkb_U1->dout(grp_fu_219_p2);
    ShuffleNetV2_fmulcud_U2 = new ShuffleNetV2_fmulcud<1,4,32,32,32>("ShuffleNetV2_fmulcud_U2");
    ShuffleNetV2_fmulcud_U2->clk(ap_clk);
    ShuffleNetV2_fmulcud_U2->reset(ap_rst);
    ShuffleNetV2_fmulcud_U2->din0(weight_load_reg_819);
    ShuffleNetV2_fmulcud_U2->din1(tmp_121_reg_824);
    ShuffleNetV2_fmulcud_U2->ce(ap_var_for_const0);
    ShuffleNetV2_fmulcud_U2->dout(grp_fu_225_p2);
    ShuffleNetV2_fcmpdEe_U3 = new ShuffleNetV2_fcmpdEe<1,1,32,32,1>("ShuffleNetV2_fcmpdEe_U3");
    ShuffleNetV2_fcmpdEe_U3->din0(result_reg_844);
    ShuffleNetV2_fcmpdEe_U3->din1(ap_var_for_const1);
    ShuffleNetV2_fcmpdEe_U3->opcode(ap_var_for_const2);
    ShuffleNetV2_fcmpdEe_U3->dout(tmp_39_fu_229_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_234_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_234_p2 );

    SC_METHOD(thread_bias_address0);
    sensitive << ( bias_addr_reg_689 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_bias_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ci_8_fu_350_p2);
    sensitive << ( ci_reg_162 );

    SC_METHOD(thread_co_23_fu_240_p2);
    sensitive << ( co_reg_115 );

    SC_METHOD(thread_exitcond1_fu_412_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( m_reg_185 );

    SC_METHOD(thread_exitcond2_fu_344_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ci_reg_162 );

    SC_METHOD(thread_exitcond3_fu_326_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( w_reg_138 );

    SC_METHOD(thread_exitcond4_fu_293_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( h_reg_126 );

    SC_METHOD(thread_exitcond5_fu_234_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( co_reg_115 );

    SC_METHOD(thread_exitcond_fu_523_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( n_reg_208 );

    SC_METHOD(thread_grp_fu_219_p0);
    sensitive << ( sum_reg_150 );
    sensitive << ( sum_2_reg_196 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_grp_fu_219_p1);
    sensitive << ( tmp_122_reg_829 );
    sensitive << ( bias_load_reg_839 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_h_23_fu_299_p2);
    sensitive << ( h_reg_126 );

    SC_METHOD(thread_h_cast_fu_289_p1);
    sensitive << ( h_reg_126 );

    SC_METHOD(thread_icmp5_fu_569_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_fu_523_p2 );
    sensitive << ( tmp_110_fu_559_p4 );

    SC_METHOD(thread_icmp_fu_513_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond1_fu_412_p2 );
    sensitive << ( tmp_108_fu_503_p4 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_362_cast_fu_593_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_m_7_fu_418_p2);
    sensitive << ( m_reg_185 );

    SC_METHOD(thread_m_cast_cast_fu_408_p1);
    sensitive << ( m_reg_185 );

    SC_METHOD(thread_n_7_fu_529_p2);
    sensitive << ( n_reg_208 );

    SC_METHOD(thread_n_cast9_fu_519_p1);
    sensitive << ( n_reg_208 );

    SC_METHOD(thread_notlhs1_fu_636_p2);
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( tmp_36_fu_622_p4 );

    SC_METHOD(thread_notlhs_fu_584_p2);
    sensitive << ( tmp_109_reg_725 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_fu_523_p2 );
    sensitive << ( n_cast9_fu_519_p1 );

    SC_METHOD(thread_notrhs1_fu_642_p2);
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( tmp_104_fu_632_p1 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( tmp_349_cast_fu_667_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( result_reg_844 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( tmp_40_fu_654_p2 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_p_shl1_fu_389_p1);
    sensitive << ( tmp_105_fu_381_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_441_p3);
    sensitive << ( tmp_107_fu_437_p1 );

    SC_METHOD(thread_p_shl_cast_fu_263_p1);
    sensitive << ( tmp_s_fu_255_p3 );

    SC_METHOD(thread_result_to_int_fu_619_p1);
    sensitive << ( result_reg_844 );

    SC_METHOD(thread_sel_tmp2_fu_605_p2);
    sensitive << ( tmp7_fu_601_p2 );
    sensitive << ( tmp6_fu_597_p2 );

    SC_METHOD(thread_tmp4_cast_fu_477_p1);
    sensitive << ( tmp4_fu_471_p2 );

    SC_METHOD(thread_tmp4_fu_471_p2);
    sensitive << ( m_reg_185 );

    SC_METHOD(thread_tmp5_cast_fu_550_p1);
    sensitive << ( tmp5_fu_544_p2 );

    SC_METHOD(thread_tmp5_fu_544_p2);
    sensitive << ( n_reg_208 );

    SC_METHOD(thread_tmp6_fu_597_p2);
    sensitive << ( icmp_reg_776 );
    sensitive << ( notlhs_reg_804 );

    SC_METHOD(thread_tmp7_fu_601_p2);
    sensitive << ( tmp_114_reg_766 );
    sensitive << ( icmp5_reg_794 );

    SC_METHOD(thread_tmp_104_fu_632_p1);
    sensitive << ( result_to_int_fu_619_p1 );

    SC_METHOD(thread_tmp_105_fu_381_p3);
    sensitive << ( tmp_200_fu_372_p2 );

    SC_METHOD(thread_tmp_106_fu_433_p1);
    sensitive << ( tmp_202_fu_428_p2 );

    SC_METHOD(thread_tmp_107_fu_437_p1);
    sensitive << ( tmp_202_fu_428_p2 );

    SC_METHOD(thread_tmp_108_fu_503_p4);
    sensitive << ( tmp_115_fu_481_p2 );

    SC_METHOD(thread_tmp_109_fu_338_p2);
    sensitive << ( w_reg_138 );

    SC_METHOD(thread_tmp_110_cast_fu_399_p1);
    sensitive << ( w_reg_138 );

    SC_METHOD(thread_tmp_110_fu_559_p4);
    sensitive << ( tmp_118_fu_554_p2 );

    SC_METHOD(thread_tmp_111_cast_fu_356_p1);
    sensitive << ( ci_reg_162 );

    SC_METHOD(thread_tmp_112_fu_424_p1);
    sensitive << ( m_reg_185 );

    SC_METHOD(thread_tmp_113_cast_fu_461_p1);
    sensitive << ( tmp_113_fu_455_p2 );

    SC_METHOD(thread_tmp_113_fu_455_p2);
    sensitive << ( m_cast_cast_fu_408_p1 );

    SC_METHOD(thread_tmp_114_fu_465_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond1_fu_412_p2 );
    sensitive << ( h_reg_126 );
    sensitive << ( tmp_113_cast_fu_461_p1 );

    SC_METHOD(thread_tmp_115_fu_481_p2);
    sensitive << ( h_cast_reg_694 );
    sensitive << ( tmp4_cast_fu_477_p1 );

    SC_METHOD(thread_tmp_116_cast_fu_486_p1);
    sensitive << ( tmp_115_fu_481_p2 );

    SC_METHOD(thread_tmp_117_cast_fu_535_p1);
    sensitive << ( n_reg_208 );

    SC_METHOD(thread_tmp_118_fu_554_p2);
    sensitive << ( w_cast_reg_712 );
    sensitive << ( tmp5_cast_fu_550_p1 );

    SC_METHOD(thread_tmp_120_cast_fu_575_p1);
    sensitive << ( tmp_118_fu_554_p2 );

    SC_METHOD(thread_tmp_121_fu_611_p3);
    sensitive << ( input_r_q0 );
    sensitive << ( sel_tmp2_fu_605_p2 );

    SC_METHOD(thread_tmp_195_fu_267_p2);
    sensitive << ( p_shl_cast_fu_263_p1 );
    sensitive << ( tmp_cast_fu_251_p1 );

    SC_METHOD(thread_tmp_196_fu_277_p3);
    sensitive << ( co_reg_115 );

    SC_METHOD(thread_tmp_197_fu_309_p2);
    sensitive << ( tmp_345_cast_reg_684 );
    sensitive << ( tmp_cast_84_fu_305_p1 );

    SC_METHOD(thread_tmp_198_fu_403_p2);
    sensitive << ( tmp_348_cast_reg_707 );
    sensitive << ( tmp_110_cast_fu_399_p1 );

    SC_METHOD(thread_tmp_199_fu_360_p3);
    sensitive << ( ci_reg_162 );

    SC_METHOD(thread_tmp_200_fu_372_p2);
    sensitive << ( tmp_343_cast_reg_679 );
    sensitive << ( tmp_111_cast_fu_356_p1 );

    SC_METHOD(thread_tmp_201_fu_393_p2);
    sensitive << ( p_shl1_fu_389_p1 );
    sensitive << ( tmp_352_cast_fu_377_p1 );

    SC_METHOD(thread_tmp_202_fu_428_p2);
    sensitive << ( tmp_201_reg_743 );
    sensitive << ( tmp_112_fu_424_p1 );

    SC_METHOD(thread_tmp_203_fu_449_p2);
    sensitive << ( p_shl2_cast_fu_441_p3 );
    sensitive << ( tmp_106_fu_433_p1 );

    SC_METHOD(thread_tmp_204_fu_490_p2);
    sensitive << ( tmp_351_cast_reg_738 );
    sensitive << ( tmp_116_cast_fu_486_p1 );

    SC_METHOD(thread_tmp_205_fu_539_p2);
    sensitive << ( tmp_203_reg_761 );
    sensitive << ( tmp_117_cast_fu_535_p1 );

    SC_METHOD(thread_tmp_206_fu_579_p2);
    sensitive << ( tmp_360_cast_reg_771 );
    sensitive << ( tmp_120_cast_fu_575_p1 );

    SC_METHOD(thread_tmp_343_cast_fu_273_p1);
    sensitive << ( tmp_195_fu_267_p2 );

    SC_METHOD(thread_tmp_345_cast_fu_285_p1);
    sensitive << ( tmp_196_fu_277_p3 );

    SC_METHOD(thread_tmp_348_cast_fu_314_p3);
    sensitive << ( tmp_197_fu_309_p2 );

    SC_METHOD(thread_tmp_349_cast_fu_667_p1);
    sensitive << ( tmp_198_reg_748 );

    SC_METHOD(thread_tmp_351_cast_fu_368_p1);
    sensitive << ( tmp_199_fu_360_p3 );

    SC_METHOD(thread_tmp_352_cast_fu_377_p1);
    sensitive << ( tmp_200_fu_372_p2 );

    SC_METHOD(thread_tmp_360_cast_fu_495_p3);
    sensitive << ( tmp_204_fu_490_p2 );

    SC_METHOD(thread_tmp_361_cast_fu_589_p1);
    sensitive << ( tmp_205_reg_789 );

    SC_METHOD(thread_tmp_362_cast_fu_593_p1);
    sensitive << ( tmp_206_reg_799 );

    SC_METHOD(thread_tmp_36_fu_622_p4);
    sensitive << ( result_to_int_fu_619_p1 );

    SC_METHOD(thread_tmp_38_fu_648_p2);
    sensitive << ( notrhs1_fu_642_p2 );
    sensitive << ( notlhs1_fu_636_p2 );

    SC_METHOD(thread_tmp_40_fu_654_p2);
    sensitive << ( tmp_39_reg_851 );
    sensitive << ( tmp_38_fu_648_p2 );

    SC_METHOD(thread_tmp_cast_84_fu_305_p1);
    sensitive << ( h_reg_126 );

    SC_METHOD(thread_tmp_cast_fu_251_p1);
    sensitive << ( co_reg_115 );

    SC_METHOD(thread_tmp_fu_246_p1);
    sensitive << ( co_reg_115 );

    SC_METHOD(thread_tmp_s_fu_255_p3);
    sensitive << ( co_reg_115 );

    SC_METHOD(thread_w_23_fu_332_p2);
    sensitive << ( w_reg_138 );

    SC_METHOD(thread_w_cast_fu_322_p1);
    sensitive << ( w_reg_138 );

    SC_METHOD(thread_weight_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_361_cast_fu_589_p1 );

    SC_METHOD(thread_weight_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_234_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond4_fu_293_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond3_fu_326_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond2_fu_344_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond1_fu_412_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_fu_523_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    ap_CS_fsm = "00000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, weight_address0, "(port)weight_address0");
    sc_trace(mVcdFile, weight_ce0, "(port)weight_ce0");
    sc_trace(mVcdFile, weight_q0, "(port)weight_q0");
    sc_trace(mVcdFile, bias_address0, "(port)bias_address0");
    sc_trace(mVcdFile, bias_ce0, "(port)bias_ce0");
    sc_trace(mVcdFile, bias_q0, "(port)bias_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, co_23_fu_240_p2, "co_23_fu_240_p2");
    sc_trace(mVcdFile, co_23_reg_674, "co_23_reg_674");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_343_cast_fu_273_p1, "tmp_343_cast_fu_273_p1");
    sc_trace(mVcdFile, tmp_343_cast_reg_679, "tmp_343_cast_reg_679");
    sc_trace(mVcdFile, exitcond5_fu_234_p2, "exitcond5_fu_234_p2");
    sc_trace(mVcdFile, tmp_345_cast_fu_285_p1, "tmp_345_cast_fu_285_p1");
    sc_trace(mVcdFile, tmp_345_cast_reg_684, "tmp_345_cast_reg_684");
    sc_trace(mVcdFile, bias_addr_reg_689, "bias_addr_reg_689");
    sc_trace(mVcdFile, h_cast_fu_289_p1, "h_cast_fu_289_p1");
    sc_trace(mVcdFile, h_cast_reg_694, "h_cast_reg_694");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, h_23_fu_299_p2, "h_23_fu_299_p2");
    sc_trace(mVcdFile, h_23_reg_702, "h_23_reg_702");
    sc_trace(mVcdFile, tmp_348_cast_fu_314_p3, "tmp_348_cast_fu_314_p3");
    sc_trace(mVcdFile, tmp_348_cast_reg_707, "tmp_348_cast_reg_707");
    sc_trace(mVcdFile, exitcond4_fu_293_p2, "exitcond4_fu_293_p2");
    sc_trace(mVcdFile, w_cast_fu_322_p1, "w_cast_fu_322_p1");
    sc_trace(mVcdFile, w_cast_reg_712, "w_cast_reg_712");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, w_23_fu_332_p2, "w_23_fu_332_p2");
    sc_trace(mVcdFile, w_23_reg_720, "w_23_reg_720");
    sc_trace(mVcdFile, tmp_109_fu_338_p2, "tmp_109_fu_338_p2");
    sc_trace(mVcdFile, tmp_109_reg_725, "tmp_109_reg_725");
    sc_trace(mVcdFile, exitcond3_fu_326_p2, "exitcond3_fu_326_p2");
    sc_trace(mVcdFile, ci_8_fu_350_p2, "ci_8_fu_350_p2");
    sc_trace(mVcdFile, ci_8_reg_733, "ci_8_reg_733");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_351_cast_fu_368_p1, "tmp_351_cast_fu_368_p1");
    sc_trace(mVcdFile, tmp_351_cast_reg_738, "tmp_351_cast_reg_738");
    sc_trace(mVcdFile, exitcond2_fu_344_p2, "exitcond2_fu_344_p2");
    sc_trace(mVcdFile, tmp_201_fu_393_p2, "tmp_201_fu_393_p2");
    sc_trace(mVcdFile, tmp_201_reg_743, "tmp_201_reg_743");
    sc_trace(mVcdFile, tmp_198_fu_403_p2, "tmp_198_fu_403_p2");
    sc_trace(mVcdFile, tmp_198_reg_748, "tmp_198_reg_748");
    sc_trace(mVcdFile, m_7_fu_418_p2, "m_7_fu_418_p2");
    sc_trace(mVcdFile, m_7_reg_756, "m_7_reg_756");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_203_fu_449_p2, "tmp_203_fu_449_p2");
    sc_trace(mVcdFile, tmp_203_reg_761, "tmp_203_reg_761");
    sc_trace(mVcdFile, exitcond1_fu_412_p2, "exitcond1_fu_412_p2");
    sc_trace(mVcdFile, tmp_114_fu_465_p2, "tmp_114_fu_465_p2");
    sc_trace(mVcdFile, tmp_114_reg_766, "tmp_114_reg_766");
    sc_trace(mVcdFile, tmp_360_cast_fu_495_p3, "tmp_360_cast_fu_495_p3");
    sc_trace(mVcdFile, tmp_360_cast_reg_771, "tmp_360_cast_reg_771");
    sc_trace(mVcdFile, icmp_fu_513_p2, "icmp_fu_513_p2");
    sc_trace(mVcdFile, icmp_reg_776, "icmp_reg_776");
    sc_trace(mVcdFile, n_7_fu_529_p2, "n_7_fu_529_p2");
    sc_trace(mVcdFile, n_7_reg_784, "n_7_reg_784");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_205_fu_539_p2, "tmp_205_fu_539_p2");
    sc_trace(mVcdFile, tmp_205_reg_789, "tmp_205_reg_789");
    sc_trace(mVcdFile, exitcond_fu_523_p2, "exitcond_fu_523_p2");
    sc_trace(mVcdFile, icmp5_fu_569_p2, "icmp5_fu_569_p2");
    sc_trace(mVcdFile, icmp5_reg_794, "icmp5_reg_794");
    sc_trace(mVcdFile, tmp_206_fu_579_p2, "tmp_206_fu_579_p2");
    sc_trace(mVcdFile, tmp_206_reg_799, "tmp_206_reg_799");
    sc_trace(mVcdFile, notlhs_fu_584_p2, "notlhs_fu_584_p2");
    sc_trace(mVcdFile, notlhs_reg_804, "notlhs_reg_804");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, weight_load_reg_819, "weight_load_reg_819");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_121_fu_611_p3, "tmp_121_fu_611_p3");
    sc_trace(mVcdFile, tmp_121_reg_824, "tmp_121_reg_824");
    sc_trace(mVcdFile, grp_fu_225_p2, "grp_fu_225_p2");
    sc_trace(mVcdFile, tmp_122_reg_829, "tmp_122_reg_829");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, grp_fu_219_p2, "grp_fu_219_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, bias_load_reg_839, "bias_load_reg_839");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, result_reg_844, "result_reg_844");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, tmp_39_fu_229_p2, "tmp_39_fu_229_p2");
    sc_trace(mVcdFile, tmp_39_reg_851, "tmp_39_reg_851");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, co_reg_115, "co_reg_115");
    sc_trace(mVcdFile, h_reg_126, "h_reg_126");
    sc_trace(mVcdFile, w_reg_138, "w_reg_138");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, sum_reg_150, "sum_reg_150");
    sc_trace(mVcdFile, ci_reg_162, "ci_reg_162");
    sc_trace(mVcdFile, sum_1_reg_173, "sum_1_reg_173");
    sc_trace(mVcdFile, m_reg_185, "m_reg_185");
    sc_trace(mVcdFile, sum_2_reg_196, "sum_2_reg_196");
    sc_trace(mVcdFile, n_reg_208, "n_reg_208");
    sc_trace(mVcdFile, tmp_fu_246_p1, "tmp_fu_246_p1");
    sc_trace(mVcdFile, tmp_361_cast_fu_589_p1, "tmp_361_cast_fu_589_p1");
    sc_trace(mVcdFile, tmp_362_cast_fu_593_p1, "tmp_362_cast_fu_593_p1");
    sc_trace(mVcdFile, tmp_349_cast_fu_667_p1, "tmp_349_cast_fu_667_p1");
    sc_trace(mVcdFile, grp_fu_219_p0, "grp_fu_219_p0");
    sc_trace(mVcdFile, grp_fu_219_p1, "grp_fu_219_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_s_fu_255_p3, "tmp_s_fu_255_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_263_p1, "p_shl_cast_fu_263_p1");
    sc_trace(mVcdFile, tmp_cast_fu_251_p1, "tmp_cast_fu_251_p1");
    sc_trace(mVcdFile, tmp_195_fu_267_p2, "tmp_195_fu_267_p2");
    sc_trace(mVcdFile, tmp_196_fu_277_p3, "tmp_196_fu_277_p3");
    sc_trace(mVcdFile, tmp_cast_84_fu_305_p1, "tmp_cast_84_fu_305_p1");
    sc_trace(mVcdFile, tmp_197_fu_309_p2, "tmp_197_fu_309_p2");
    sc_trace(mVcdFile, tmp_199_fu_360_p3, "tmp_199_fu_360_p3");
    sc_trace(mVcdFile, tmp_111_cast_fu_356_p1, "tmp_111_cast_fu_356_p1");
    sc_trace(mVcdFile, tmp_200_fu_372_p2, "tmp_200_fu_372_p2");
    sc_trace(mVcdFile, tmp_105_fu_381_p3, "tmp_105_fu_381_p3");
    sc_trace(mVcdFile, p_shl1_fu_389_p1, "p_shl1_fu_389_p1");
    sc_trace(mVcdFile, tmp_352_cast_fu_377_p1, "tmp_352_cast_fu_377_p1");
    sc_trace(mVcdFile, tmp_110_cast_fu_399_p1, "tmp_110_cast_fu_399_p1");
    sc_trace(mVcdFile, tmp_112_fu_424_p1, "tmp_112_fu_424_p1");
    sc_trace(mVcdFile, tmp_202_fu_428_p2, "tmp_202_fu_428_p2");
    sc_trace(mVcdFile, tmp_107_fu_437_p1, "tmp_107_fu_437_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_441_p3, "p_shl2_cast_fu_441_p3");
    sc_trace(mVcdFile, tmp_106_fu_433_p1, "tmp_106_fu_433_p1");
    sc_trace(mVcdFile, m_cast_cast_fu_408_p1, "m_cast_cast_fu_408_p1");
    sc_trace(mVcdFile, tmp_113_fu_455_p2, "tmp_113_fu_455_p2");
    sc_trace(mVcdFile, tmp_113_cast_fu_461_p1, "tmp_113_cast_fu_461_p1");
    sc_trace(mVcdFile, tmp4_fu_471_p2, "tmp4_fu_471_p2");
    sc_trace(mVcdFile, tmp4_cast_fu_477_p1, "tmp4_cast_fu_477_p1");
    sc_trace(mVcdFile, tmp_115_fu_481_p2, "tmp_115_fu_481_p2");
    sc_trace(mVcdFile, tmp_116_cast_fu_486_p1, "tmp_116_cast_fu_486_p1");
    sc_trace(mVcdFile, tmp_204_fu_490_p2, "tmp_204_fu_490_p2");
    sc_trace(mVcdFile, tmp_108_fu_503_p4, "tmp_108_fu_503_p4");
    sc_trace(mVcdFile, tmp_117_cast_fu_535_p1, "tmp_117_cast_fu_535_p1");
    sc_trace(mVcdFile, tmp5_fu_544_p2, "tmp5_fu_544_p2");
    sc_trace(mVcdFile, tmp5_cast_fu_550_p1, "tmp5_cast_fu_550_p1");
    sc_trace(mVcdFile, tmp_118_fu_554_p2, "tmp_118_fu_554_p2");
    sc_trace(mVcdFile, tmp_110_fu_559_p4, "tmp_110_fu_559_p4");
    sc_trace(mVcdFile, tmp_120_cast_fu_575_p1, "tmp_120_cast_fu_575_p1");
    sc_trace(mVcdFile, n_cast9_fu_519_p1, "n_cast9_fu_519_p1");
    sc_trace(mVcdFile, tmp7_fu_601_p2, "tmp7_fu_601_p2");
    sc_trace(mVcdFile, tmp6_fu_597_p2, "tmp6_fu_597_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_605_p2, "sel_tmp2_fu_605_p2");
    sc_trace(mVcdFile, result_to_int_fu_619_p1, "result_to_int_fu_619_p1");
    sc_trace(mVcdFile, tmp_36_fu_622_p4, "tmp_36_fu_622_p4");
    sc_trace(mVcdFile, tmp_104_fu_632_p1, "tmp_104_fu_632_p1");
    sc_trace(mVcdFile, notrhs1_fu_642_p2, "notrhs1_fu_642_p2");
    sc_trace(mVcdFile, notlhs1_fu_636_p2, "notlhs1_fu_636_p2");
    sc_trace(mVcdFile, tmp_38_fu_648_p2, "tmp_38_fu_648_p2");
    sc_trace(mVcdFile, tmp_40_fu_654_p2, "tmp_40_fu_654_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

conv1::~conv1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete ShuffleNetV2_faddbkb_U1;
    delete ShuffleNetV2_fmulcud_U2;
    delete ShuffleNetV2_fcmpdEe_U3;
}

void conv1::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void conv1::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_0;
}

void conv1::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv5_2;
}

void conv1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_412_p2.read()))) {
        ci_reg_162 = ci_8_reg_733.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_326_p2.read()))) {
        ci_reg_162 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond4_fu_293_p2.read(), ap_const_lv1_1))) {
        co_reg_115 = co_23_reg_674.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        co_reg_115 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_326_p2.read(), ap_const_lv1_1))) {
        h_reg_126 = h_23_reg_702.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond5_fu_234_p2.read(), ap_const_lv1_0))) {
        h_reg_126 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_523_p2.read()))) {
        m_reg_185 = m_7_reg_756.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_344_p2.read()))) {
        m_reg_185 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_412_p2.read()))) {
        n_reg_208 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        n_reg_208 = n_7_reg_784.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_523_p2.read()))) {
        sum_1_reg_173 = sum_2_reg_196.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_344_p2.read()))) {
        sum_1_reg_173 = sum_reg_150.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_412_p2.read()))) {
        sum_2_reg_196 = sum_1_reg_173.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        sum_2_reg_196 = grp_fu_219_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_412_p2.read()))) {
        sum_reg_150 = sum_1_reg_173.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_326_p2.read()))) {
        sum_reg_150 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_293_p2.read()))) {
        w_reg_138 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        w_reg_138 = w_23_reg_720.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond5_fu_234_p2.read(), ap_const_lv1_0))) {
        bias_addr_reg_689 =  (sc_lv<5>) (tmp_fu_246_p1.read());
        tmp_343_cast_reg_679 = tmp_343_cast_fu_273_p1.read();
        tmp_345_cast_reg_684 = tmp_345_cast_fu_285_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        bias_load_reg_839 = bias_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        ci_8_reg_733 = ci_8_fu_350_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        co_23_reg_674 = co_23_fu_240_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        h_23_reg_702 = h_23_fu_299_p2.read();
        h_cast_reg_694 = h_cast_fu_289_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_523_p2.read()))) {
        icmp5_reg_794 = icmp5_fu_569_p2.read();
        notlhs_reg_804 = notlhs_fu_584_p2.read();
        tmp_205_reg_789 = tmp_205_fu_539_p2.read();
        tmp_206_reg_799 = tmp_206_fu_579_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_412_p2.read()))) {
        icmp_reg_776 = icmp_fu_513_p2.read();
        tmp_114_reg_766 = tmp_114_fu_465_p2.read();
        tmp_203_reg_761 = tmp_203_fu_449_p2.read();
        tmp_360_cast_reg_771 = tmp_360_cast_fu_495_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        m_7_reg_756 = m_7_fu_418_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        n_7_reg_784 = n_7_fu_529_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        result_reg_844 = grp_fu_219_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_326_p2.read()))) {
        tmp_109_reg_725 = tmp_109_fu_338_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        tmp_121_reg_824 = tmp_121_fu_611_p3.read();
        weight_load_reg_819 = weight_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        tmp_122_reg_829 = grp_fu_225_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond2_fu_344_p2.read(), ap_const_lv1_1))) {
        tmp_198_reg_748 = tmp_198_fu_403_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_344_p2.read()))) {
        tmp_201_reg_743 = tmp_201_fu_393_p2.read();
        tmp_351_cast_reg_738 = tmp_351_cast_fu_368_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_293_p2.read()))) {
        tmp_348_cast_reg_707 = tmp_348_cast_fu_314_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        tmp_39_reg_851 = tmp_39_fu_229_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        w_23_reg_720 = w_23_fu_332_p2.read();
        w_cast_reg_712 = w_cast_fu_322_p1.read();
    }
}

void conv1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv1::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void conv1::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void conv1::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void conv1::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void conv1::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void conv1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv1::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void conv1::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void conv1::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void conv1::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void conv1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv1::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void conv1::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void conv1::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond5_fu_234_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_234_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv1::thread_bias_address0() {
    bias_address0 = bias_addr_reg_689.read();
}

void conv1::thread_bias_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        bias_ce0 = ap_const_logic_1;
    } else {
        bias_ce0 = ap_const_logic_0;
    }
}

void conv1::thread_ci_8_fu_350_p2() {
    ci_8_fu_350_p2 = (!ci_reg_162.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(ci_reg_162.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv1::thread_co_23_fu_240_p2() {
    co_23_fu_240_p2 = (!co_reg_115.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(co_reg_115.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv1::thread_exitcond1_fu_412_p2() {
    exitcond1_fu_412_p2 = (!m_reg_185.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(m_reg_185.read() == ap_const_lv2_3);
}

void conv1::thread_exitcond2_fu_344_p2() {
    exitcond2_fu_344_p2 = (!ci_reg_162.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(ci_reg_162.read() == ap_const_lv2_3);
}

void conv1::thread_exitcond3_fu_326_p2() {
    exitcond3_fu_326_p2 = (!w_reg_138.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(w_reg_138.read() == ap_const_lv6_20);
}

void conv1::thread_exitcond4_fu_293_p2() {
    exitcond4_fu_293_p2 = (!h_reg_126.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(h_reg_126.read() == ap_const_lv6_20);
}

void conv1::thread_exitcond5_fu_234_p2() {
    exitcond5_fu_234_p2 = (!co_reg_115.read().is_01() || !ap_const_lv5_18.is_01())? sc_lv<1>(): sc_lv<1>(co_reg_115.read() == ap_const_lv5_18);
}

void conv1::thread_exitcond_fu_523_p2() {
    exitcond_fu_523_p2 = (!n_reg_208.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(n_reg_208.read() == ap_const_lv2_3);
}

void conv1::thread_grp_fu_219_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_219_p0 = sum_reg_150.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_fu_219_p0 = sum_2_reg_196.read();
    } else {
        grp_fu_219_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void conv1::thread_grp_fu_219_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_219_p1 = bias_load_reg_839.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_fu_219_p1 = tmp_122_reg_829.read();
    } else {
        grp_fu_219_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void conv1::thread_h_23_fu_299_p2() {
    h_23_fu_299_p2 = (!h_reg_126.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(h_reg_126.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void conv1::thread_h_cast_fu_289_p1() {
    h_cast_fu_289_p1 = esl_zext<7,6>(h_reg_126.read());
}

void conv1::thread_icmp5_fu_569_p2() {
    icmp5_fu_569_p2 = (!tmp_110_fu_559_p4.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_110_fu_559_p4.read() != ap_const_lv2_1);
}

void conv1::thread_icmp_fu_513_p2() {
    icmp_fu_513_p2 = (!tmp_108_fu_503_p4.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_108_fu_503_p4.read() != ap_const_lv2_1);
}

void conv1::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<12>) (tmp_362_cast_fu_593_p1.read());
}

void conv1::thread_input_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void conv1::thread_m_7_fu_418_p2() {
    m_7_fu_418_p2 = (!m_reg_185.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(m_reg_185.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv1::thread_m_cast_cast_fu_408_p1() {
    m_cast_cast_fu_408_p1 = esl_zext<3,2>(m_reg_185.read());
}

void conv1::thread_n_7_fu_529_p2() {
    n_7_fu_529_p2 = (!n_reg_208.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(n_reg_208.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv1::thread_n_cast9_fu_519_p1() {
    n_cast9_fu_519_p1 = esl_zext<6,2>(n_reg_208.read());
}

void conv1::thread_notlhs1_fu_636_p2() {
    notlhs1_fu_636_p2 = (!tmp_36_fu_622_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_36_fu_622_p4.read() != ap_const_lv8_FF);
}

void conv1::thread_notlhs_fu_584_p2() {
    notlhs_fu_584_p2 = (!n_cast9_fu_519_p1.read().is_01() || !tmp_109_reg_725.read().is_01())? sc_lv<1>(): sc_lv<1>(n_cast9_fu_519_p1.read() != tmp_109_reg_725.read());
}

void conv1::thread_notrhs1_fu_642_p2() {
    notrhs1_fu_642_p2 = (!tmp_104_fu_632_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_104_fu_632_p1.read() == ap_const_lv23_0);
}

void conv1::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<15>) (tmp_349_cast_fu_667_p1.read());
}

void conv1::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void conv1::thread_output_r_d0() {
    output_r_d0 = (!tmp_40_fu_654_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_40_fu_654_p2.read()[0].to_bool())? result_reg_844.read(): ap_const_lv32_0);
}

void conv1::thread_output_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void conv1::thread_p_shl1_fu_389_p1() {
    p_shl1_fu_389_p1 = esl_sext<64,11>(tmp_105_fu_381_p3.read());
}

void conv1::thread_p_shl2_cast_fu_441_p3() {
    p_shl2_cast_fu_441_p3 = esl_concat<9,2>(tmp_107_fu_437_p1.read(), ap_const_lv2_0);
}

void conv1::thread_p_shl_cast_fu_263_p1() {
    p_shl_cast_fu_263_p1 = esl_zext<8,7>(tmp_s_fu_255_p3.read());
}

void conv1::thread_result_to_int_fu_619_p1() {
    result_to_int_fu_619_p1 = result_reg_844.read();
}

void conv1::thread_sel_tmp2_fu_605_p2() {
    sel_tmp2_fu_605_p2 = (tmp7_fu_601_p2.read() & tmp6_fu_597_p2.read());
}

void conv1::thread_tmp4_cast_fu_477_p1() {
    tmp4_cast_fu_477_p1 = esl_sext<7,2>(tmp4_fu_471_p2.read());
}

void conv1::thread_tmp4_fu_471_p2() {
    tmp4_fu_471_p2 = (!ap_const_lv2_3.is_01() || !m_reg_185.read().is_01())? sc_lv<2>(): (sc_bigint<2>(ap_const_lv2_3) + sc_biguint<2>(m_reg_185.read()));
}

void conv1::thread_tmp5_cast_fu_550_p1() {
    tmp5_cast_fu_550_p1 = esl_sext<7,2>(tmp5_fu_544_p2.read());
}

void conv1::thread_tmp5_fu_544_p2() {
    tmp5_fu_544_p2 = (!n_reg_208.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<2>(): (sc_biguint<2>(n_reg_208.read()) + sc_bigint<2>(ap_const_lv2_3));
}

void conv1::thread_tmp6_fu_597_p2() {
    tmp6_fu_597_p2 = (icmp_reg_776.read() & notlhs_reg_804.read());
}

void conv1::thread_tmp7_fu_601_p2() {
    tmp7_fu_601_p2 = (tmp_114_reg_766.read() & icmp5_reg_794.read());
}

void conv1::thread_tmp_104_fu_632_p1() {
    tmp_104_fu_632_p1 = result_to_int_fu_619_p1.read().range(23-1, 0);
}

void conv1::thread_tmp_105_fu_381_p3() {
    tmp_105_fu_381_p3 = esl_concat<9,2>(tmp_200_fu_372_p2.read(), ap_const_lv2_0);
}

void conv1::thread_tmp_106_fu_433_p1() {
    tmp_106_fu_433_p1 = tmp_202_fu_428_p2.read().range(11-1, 0);
}

void conv1::thread_tmp_107_fu_437_p1() {
    tmp_107_fu_437_p1 = tmp_202_fu_428_p2.read().range(9-1, 0);
}

void conv1::thread_tmp_108_fu_503_p4() {
    tmp_108_fu_503_p4 = tmp_115_fu_481_p2.read().range(6, 5);
}

void conv1::thread_tmp_109_fu_338_p2() {
    tmp_109_fu_338_p2 = (!ap_const_lv6_0.is_01() || !w_reg_138.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_0) - sc_biguint<6>(w_reg_138.read()));
}

void conv1::thread_tmp_110_cast_fu_399_p1() {
    tmp_110_cast_fu_399_p1 = esl_zext<16,6>(w_reg_138.read());
}

void conv1::thread_tmp_110_fu_559_p4() {
    tmp_110_fu_559_p4 = tmp_118_fu_554_p2.read().range(6, 5);
}

void conv1::thread_tmp_111_cast_fu_356_p1() {
    tmp_111_cast_fu_356_p1 = esl_zext<9,2>(ci_reg_162.read());
}

void conv1::thread_tmp_112_fu_424_p1() {
    tmp_112_fu_424_p1 = esl_zext<64,2>(m_reg_185.read());
}

void conv1::thread_tmp_113_cast_fu_461_p1() {
    tmp_113_cast_fu_461_p1 = esl_sext<6,3>(tmp_113_fu_455_p2.read());
}

void conv1::thread_tmp_113_fu_455_p2() {
    tmp_113_fu_455_p2 = (!ap_const_lv3_0.is_01() || !m_cast_cast_fu_408_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_0) - sc_biguint<3>(m_cast_cast_fu_408_p1.read()));
}

void conv1::thread_tmp_114_fu_465_p2() {
    tmp_114_fu_465_p2 = (!h_reg_126.read().is_01() || !tmp_113_cast_fu_461_p1.read().is_01())? sc_lv<1>(): sc_lv<1>(h_reg_126.read() != tmp_113_cast_fu_461_p1.read());
}

void conv1::thread_tmp_115_fu_481_p2() {
    tmp_115_fu_481_p2 = (!tmp4_cast_fu_477_p1.read().is_01() || !h_cast_reg_694.read().is_01())? sc_lv<7>(): (sc_bigint<7>(tmp4_cast_fu_477_p1.read()) + sc_biguint<7>(h_cast_reg_694.read()));
}

void conv1::thread_tmp_116_cast_fu_486_p1() {
    tmp_116_cast_fu_486_p1 = esl_sext<8,7>(tmp_115_fu_481_p2.read());
}

void conv1::thread_tmp_117_cast_fu_535_p1() {
    tmp_117_cast_fu_535_p1 = esl_zext<11,2>(n_reg_208.read());
}

void conv1::thread_tmp_118_fu_554_p2() {
    tmp_118_fu_554_p2 = (!w_cast_reg_712.read().is_01() || !tmp5_cast_fu_550_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(w_cast_reg_712.read()) + sc_bigint<7>(tmp5_cast_fu_550_p1.read()));
}

void conv1::thread_tmp_120_cast_fu_575_p1() {
    tmp_120_cast_fu_575_p1 = esl_sext<13,7>(tmp_118_fu_554_p2.read());
}

void conv1::thread_tmp_121_fu_611_p3() {
    tmp_121_fu_611_p3 = (!sel_tmp2_fu_605_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp2_fu_605_p2.read()[0].to_bool())? input_r_q0.read(): ap_const_lv32_0);
}

void conv1::thread_tmp_195_fu_267_p2() {
    tmp_195_fu_267_p2 = (!p_shl_cast_fu_263_p1.read().is_01() || !tmp_cast_fu_251_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_shl_cast_fu_263_p1.read()) - sc_biguint<8>(tmp_cast_fu_251_p1.read()));
}

void conv1::thread_tmp_196_fu_277_p3() {
    tmp_196_fu_277_p3 = esl_concat<5,5>(co_reg_115.read(), ap_const_lv5_0);
}

void conv1::thread_tmp_197_fu_309_p2() {
    tmp_197_fu_309_p2 = (!tmp_cast_84_fu_305_p1.read().is_01() || !tmp_345_cast_reg_684.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_cast_84_fu_305_p1.read()) + sc_biguint<11>(tmp_345_cast_reg_684.read()));
}

void conv1::thread_tmp_198_fu_403_p2() {
    tmp_198_fu_403_p2 = (!tmp_348_cast_reg_707.read().is_01() || !tmp_110_cast_fu_399_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_348_cast_reg_707.read()) + sc_biguint<16>(tmp_110_cast_fu_399_p1.read()));
}

void conv1::thread_tmp_199_fu_360_p3() {
    tmp_199_fu_360_p3 = esl_concat<2,5>(ci_reg_162.read(), ap_const_lv5_0);
}

void conv1::thread_tmp_200_fu_372_p2() {
    tmp_200_fu_372_p2 = (!tmp_111_cast_fu_356_p1.read().is_01() || !tmp_343_cast_reg_679.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_111_cast_fu_356_p1.read()) + sc_bigint<9>(tmp_343_cast_reg_679.read()));
}

void conv1::thread_tmp_201_fu_393_p2() {
    tmp_201_fu_393_p2 = (!p_shl1_fu_389_p1.read().is_01() || !tmp_352_cast_fu_377_p1.read().is_01())? sc_lv<64>(): (sc_bigint<64>(p_shl1_fu_389_p1.read()) - sc_bigint<64>(tmp_352_cast_fu_377_p1.read()));
}

void conv1::thread_tmp_202_fu_428_p2() {
    tmp_202_fu_428_p2 = (!tmp_112_fu_424_p1.read().is_01() || !tmp_201_reg_743.read().is_01())? sc_lv<64>(): (sc_biguint<64>(tmp_112_fu_424_p1.read()) + sc_biguint<64>(tmp_201_reg_743.read()));
}

void conv1::thread_tmp_203_fu_449_p2() {
    tmp_203_fu_449_p2 = (!p_shl2_cast_fu_441_p3.read().is_01() || !tmp_106_fu_433_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl2_cast_fu_441_p3.read()) - sc_biguint<11>(tmp_106_fu_433_p1.read()));
}

void conv1::thread_tmp_204_fu_490_p2() {
    tmp_204_fu_490_p2 = (!tmp_116_cast_fu_486_p1.read().is_01() || !tmp_351_cast_reg_738.read().is_01())? sc_lv<8>(): (sc_bigint<8>(tmp_116_cast_fu_486_p1.read()) + sc_biguint<8>(tmp_351_cast_reg_738.read()));
}

void conv1::thread_tmp_205_fu_539_p2() {
    tmp_205_fu_539_p2 = (!tmp_203_reg_761.read().is_01() || !tmp_117_cast_fu_535_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_203_reg_761.read()) + sc_biguint<11>(tmp_117_cast_fu_535_p1.read()));
}

void conv1::thread_tmp_206_fu_579_p2() {
    tmp_206_fu_579_p2 = (!tmp_360_cast_reg_771.read().is_01() || !tmp_120_cast_fu_575_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_360_cast_reg_771.read()) + sc_bigint<13>(tmp_120_cast_fu_575_p1.read()));
}

void conv1::thread_tmp_343_cast_fu_273_p1() {
    tmp_343_cast_fu_273_p1 = esl_sext<9,8>(tmp_195_fu_267_p2.read());
}

void conv1::thread_tmp_345_cast_fu_285_p1() {
    tmp_345_cast_fu_285_p1 = esl_zext<11,10>(tmp_196_fu_277_p3.read());
}

void conv1::thread_tmp_348_cast_fu_314_p3() {
    tmp_348_cast_fu_314_p3 = esl_concat<11,5>(tmp_197_fu_309_p2.read(), ap_const_lv5_0);
}

void conv1::thread_tmp_349_cast_fu_667_p1() {
    tmp_349_cast_fu_667_p1 = esl_zext<64,16>(tmp_198_reg_748.read());
}

void conv1::thread_tmp_351_cast_fu_368_p1() {
    tmp_351_cast_fu_368_p1 = esl_zext<8,7>(tmp_199_fu_360_p3.read());
}

void conv1::thread_tmp_352_cast_fu_377_p1() {
    tmp_352_cast_fu_377_p1 = esl_sext<64,9>(tmp_200_fu_372_p2.read());
}

void conv1::thread_tmp_360_cast_fu_495_p3() {
    tmp_360_cast_fu_495_p3 = esl_concat<8,5>(tmp_204_fu_490_p2.read(), ap_const_lv5_0);
}

void conv1::thread_tmp_361_cast_fu_589_p1() {
    tmp_361_cast_fu_589_p1 = esl_zext<64,11>(tmp_205_reg_789.read());
}

void conv1::thread_tmp_362_cast_fu_593_p1() {
    tmp_362_cast_fu_593_p1 = esl_zext<64,13>(tmp_206_reg_799.read());
}

void conv1::thread_tmp_36_fu_622_p4() {
    tmp_36_fu_622_p4 = result_to_int_fu_619_p1.read().range(30, 23);
}

void conv1::thread_tmp_38_fu_648_p2() {
    tmp_38_fu_648_p2 = (notrhs1_fu_642_p2.read() | notlhs1_fu_636_p2.read());
}

void conv1::thread_tmp_40_fu_654_p2() {
    tmp_40_fu_654_p2 = (tmp_38_fu_648_p2.read() & tmp_39_reg_851.read());
}

void conv1::thread_tmp_cast_84_fu_305_p1() {
    tmp_cast_84_fu_305_p1 = esl_zext<11,6>(h_reg_126.read());
}

void conv1::thread_tmp_cast_fu_251_p1() {
    tmp_cast_fu_251_p1 = esl_zext<8,5>(co_reg_115.read());
}

void conv1::thread_tmp_fu_246_p1() {
    tmp_fu_246_p1 = esl_zext<64,5>(co_reg_115.read());
}

void conv1::thread_tmp_s_fu_255_p3() {
    tmp_s_fu_255_p3 = esl_concat<5,2>(co_reg_115.read(), ap_const_lv2_0);
}

void conv1::thread_w_23_fu_332_p2() {
    w_23_fu_332_p2 = (!w_reg_138.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(w_reg_138.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void conv1::thread_w_cast_fu_322_p1() {
    w_cast_fu_322_p1 = esl_zext<7,6>(w_reg_138.read());
}

void conv1::thread_weight_address0() {
    weight_address0 =  (sc_lv<10>) (tmp_361_cast_fu_589_p1.read());
}

void conv1::thread_weight_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        weight_ce0 = ap_const_logic_1;
    } else {
        weight_ce0 = ap_const_logic_0;
    }
}

void conv1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond5_fu_234_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond4_fu_293_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond3_fu_326_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_344_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state19;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_412_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_523_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<26>) ("XXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

