#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("image_r_address0", 12, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("image_r_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("image_r_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("conv1_weight_address0", 10, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("conv1_weight_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("conv1_weight_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("shuffle_conv_3x3_address0", 14, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("shuffle_conv_3x3_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("shuffle_conv_3x3_q0", 32, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("shuffle_conv_1x1_address0", 18, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("shuffle_conv_1x1_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("shuffle_conv_1x1_q0", 32, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("conv_last_weight_address0", 17, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("conv_last_weight_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("conv_last_weight_q0", 32, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("fc_weight_address0", 13, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("fc_weight_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("fc_weight_q0", 32, hls_in, 5, "ap_memory", "mem_dout", 1),
	Port_Property("bias_address0", 12, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("bias_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("bias_q0", 32, hls_in, 6, "ap_memory", "mem_dout", 1),
	Port_Property("fc_output_address0", 10, hls_out, 7, "ap_memory", "mem_address", 1),
	Port_Property("fc_output_ce0", 1, hls_out, 7, "ap_memory", "mem_ce", 1),
	Port_Property("fc_output_we0", 1, hls_out, 7, "ap_memory", "mem_we", 1),
	Port_Property("fc_output_d0", 32, hls_out, 7, "ap_memory", "mem_din", 1),
};
const char* HLS_Design_Meta::dut_name = "ShuffleNetV2";
