// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module subconv_1x1_32 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        weight_address0,
        weight_ce0,
        weight_q0,
        bias_address0,
        bias_ce0,
        bias_q0,
        conv1_output_address0,
        conv1_output_ce0,
        conv1_output_q0,
        ShuffleConvs_0_Downs_address0,
        ShuffleConvs_0_Downs_ce0,
        ShuffleConvs_0_Downs_we0,
        ShuffleConvs_0_Downs_d0
);

parameter    ap_ST_fsm_state1 = 23'd1;
parameter    ap_ST_fsm_state2 = 23'd2;
parameter    ap_ST_fsm_state3 = 23'd4;
parameter    ap_ST_fsm_state4 = 23'd8;
parameter    ap_ST_fsm_state5 = 23'd16;
parameter    ap_ST_fsm_state6 = 23'd32;
parameter    ap_ST_fsm_state7 = 23'd64;
parameter    ap_ST_fsm_state8 = 23'd128;
parameter    ap_ST_fsm_state9 = 23'd256;
parameter    ap_ST_fsm_state10 = 23'd512;
parameter    ap_ST_fsm_state11 = 23'd1024;
parameter    ap_ST_fsm_state12 = 23'd2048;
parameter    ap_ST_fsm_state13 = 23'd4096;
parameter    ap_ST_fsm_state14 = 23'd8192;
parameter    ap_ST_fsm_state15 = 23'd16384;
parameter    ap_ST_fsm_state16 = 23'd32768;
parameter    ap_ST_fsm_state17 = 23'd65536;
parameter    ap_ST_fsm_state18 = 23'd131072;
parameter    ap_ST_fsm_state19 = 23'd262144;
parameter    ap_ST_fsm_state20 = 23'd524288;
parameter    ap_ST_fsm_state21 = 23'd1048576;
parameter    ap_ST_fsm_state22 = 23'd2097152;
parameter    ap_ST_fsm_state23 = 23'd4194304;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] weight_address0;
output   weight_ce0;
input  [31:0] weight_q0;
output  [4:0] bias_address0;
output   bias_ce0;
input  [31:0] bias_q0;
output  [14:0] conv1_output_address0;
output   conv1_output_ce0;
input  [31:0] conv1_output_q0;
output  [14:0] ShuffleConvs_0_Downs_address0;
output   ShuffleConvs_0_Downs_ce0;
output   ShuffleConvs_0_Downs_we0;
output  [31:0] ShuffleConvs_0_Downs_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg weight_ce0;
reg bias_ce0;
reg conv1_output_ce0;
reg ShuffleConvs_0_Downs_ce0;
reg ShuffleConvs_0_Downs_we0;

(* fsm_encoding = "none" *) reg   [22:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] co_10_fu_170_p2;
reg   [4:0] co_10_reg_378;
wire    ap_CS_fsm_state2;
wire   [10:0] p_shl_cast_fu_189_p1;
reg   [10:0] p_shl_cast_reg_383;
wire   [0:0] exitcond3_fu_164_p2;
wire   [10:0] tmp_117_fu_205_p2;
reg   [10:0] tmp_117_reg_388;
reg   [4:0] bias_addr_reg_393;
wire   [5:0] h_10_fu_217_p2;
reg   [5:0] h_10_reg_401;
wire    ap_CS_fsm_state3;
wire   [10:0] tmp_cast_fu_223_p1;
reg   [10:0] tmp_cast_reg_406;
wire   [0:0] exitcond2_fu_211_p2;
wire   [15:0] tmp_177_cast_fu_232_p3;
reg   [15:0] tmp_177_cast_reg_411;
wire   [5:0] w_10_fu_246_p2;
reg   [5:0] w_10_reg_419;
wire    ap_CS_fsm_state4;
wire   [15:0] tmp_88_cast_fu_252_p1;
reg   [15:0] tmp_88_cast_reg_424;
wire   [0:0] exitcond1_fu_240_p2;
reg   [14:0] ShuffleConvs_0_Downs_reg_429;
wire   [4:0] ci_4_fu_272_p2;
reg   [4:0] ci_4_reg_437;
wire    ap_CS_fsm_state5;
wire   [0:0] exitcond_fu_266_p2;
reg   [31:0] weight_load_reg_452;
wire    ap_CS_fsm_state6;
reg   [31:0] conv1_output_load_reg_457;
wire   [31:0] grp_fu_155_p2;
reg   [31:0] tmp_90_reg_462;
wire    ap_CS_fsm_state10;
wire   [31:0] grp_fu_150_p2;
wire    ap_CS_fsm_state15;
reg   [31:0] bias_load_reg_472;
wire    ap_CS_fsm_state16;
reg   [31:0] result_reg_477;
wire    ap_CS_fsm_state21;
wire   [0:0] tmp_19_fu_159_p2;
reg   [0:0] tmp_19_reg_484;
wire    ap_CS_fsm_state22;
reg   [4:0] co_reg_94;
reg   [5:0] h_reg_105;
reg   [5:0] w_reg_116;
wire    ap_CS_fsm_state23;
reg   [31:0] sum_reg_127;
reg   [4:0] ci_reg_139;
wire   [63:0] tmp_fu_176_p1;
wire   [63:0] tmp_178_cast_fu_261_p1;
wire  signed [63:0] tmp_179_cast_fu_287_p1;
wire   [63:0] tmp_185_cast_fu_322_p1;
reg   [31:0] grp_fu_150_p1;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state7;
wire   [9:0] tmp_s_fu_181_p3;
wire   [7:0] tmp_116_fu_193_p3;
wire   [10:0] p_shl1_cast_fu_201_p1;
wire   [10:0] tmp_118_fu_227_p2;
wire   [15:0] tmp_119_fu_256_p2;
wire   [10:0] tmp_89_cast_fu_278_p1;
wire   [10:0] tmp_120_fu_282_p2;
wire   [9:0] tmp_121_fu_292_p3;
wire   [10:0] tmp_181_cast_fu_300_p1;
wire   [10:0] tmp_122_fu_304_p2;
wire   [15:0] tmp_184_cast_fu_309_p3;
wire   [15:0] tmp_123_fu_317_p2;
wire   [31:0] result_to_int_fu_327_p1;
wire   [7:0] tmp_16_fu_330_p4;
wire   [22:0] tmp_91_fu_340_p1;
wire   [0:0] notrhs_fu_350_p2;
wire   [0:0] notlhs_fu_344_p2;
wire   [0:0] tmp_18_fu_356_p2;
wire   [0:0] tmp_20_fu_362_p2;
reg   [22:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 23'd1;
end

ShuffleNetV2_faddbkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
ShuffleNetV2_faddbkb_x_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_reg_127),
    .din1(grp_fu_150_p1),
    .ce(1'b1),
    .dout(grp_fu_150_p2)
);

ShuffleNetV2_fmulcud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
ShuffleNetV2_fmulcud_x_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weight_load_reg_452),
    .din1(conv1_output_load_reg_457),
    .ce(1'b1),
    .dout(grp_fu_155_p2)
);

ShuffleNetV2_fcmpdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
ShuffleNetV2_fcmpdEe_x_U10(
    .din0(result_reg_477),
    .din1(32'd0),
    .opcode(5'd2),
    .dout(tmp_19_fu_159_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd0 == exitcond1_fu_240_p2))) begin
        ci_reg_139 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        ci_reg_139 <= ci_4_reg_437;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond2_fu_211_p2 == 1'd1))) begin
        co_reg_94 <= co_10_reg_378;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        co_reg_94 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (exitcond1_fu_240_p2 == 1'd1))) begin
        h_reg_105 <= h_10_reg_401;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_fu_164_p2 == 1'd0))) begin
        h_reg_105 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd0 == exitcond1_fu_240_p2))) begin
        sum_reg_127 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        sum_reg_127 <= grp_fu_150_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'd0 == exitcond2_fu_211_p2))) begin
        w_reg_116 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        w_reg_116 <= w_10_reg_419;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd0 == exitcond1_fu_240_p2))) begin
        ShuffleConvs_0_Downs_reg_429 <= tmp_178_cast_fu_261_p1;
        tmp_88_cast_reg_424[5 : 0] <= tmp_88_cast_fu_252_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_fu_164_p2 == 1'd0))) begin
        bias_addr_reg_393 <= tmp_fu_176_p1;
        p_shl_cast_reg_383[9 : 5] <= p_shl_cast_fu_189_p1[9 : 5];
        tmp_117_reg_388[10 : 3] <= tmp_117_fu_205_p2[10 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        bias_load_reg_472 <= bias_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ci_4_reg_437 <= ci_4_fu_272_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        co_10_reg_378 <= co_10_fu_170_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        conv1_output_load_reg_457 <= conv1_output_q0;
        weight_load_reg_452 <= weight_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        h_10_reg_401 <= h_10_fu_217_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        result_reg_477 <= grp_fu_150_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'd0 == exitcond2_fu_211_p2))) begin
        tmp_177_cast_reg_411[15 : 5] <= tmp_177_cast_fu_232_p3[15 : 5];
        tmp_cast_reg_406[5 : 0] <= tmp_cast_fu_223_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        tmp_19_reg_484 <= tmp_19_fu_159_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_90_reg_462 <= grp_fu_155_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        w_10_reg_419 <= w_10_fu_246_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        ShuffleConvs_0_Downs_ce0 = 1'b1;
    end else begin
        ShuffleConvs_0_Downs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        ShuffleConvs_0_Downs_we0 = 1'b1;
    end else begin
        ShuffleConvs_0_Downs_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state2) & (exitcond3_fu_164_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_fu_164_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_ce0 = 1'b1;
    end else begin
        bias_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        conv1_output_ce0 = 1'b1;
    end else begin
        conv1_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_150_p1 = bias_load_reg_472;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_150_p1 = tmp_90_reg_462;
    end else begin
        grp_fu_150_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        weight_ce0 = 1'b1;
    end else begin
        weight_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (exitcond3_fu_164_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (exitcond2_fu_211_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (exitcond1_fu_240_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (exitcond_fu_266_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ShuffleConvs_0_Downs_address0 = ShuffleConvs_0_Downs_reg_429;

assign ShuffleConvs_0_Downs_d0 = ((tmp_20_fu_362_p2[0:0] === 1'b1) ? result_reg_477 : 32'd0);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign bias_address0 = bias_addr_reg_393;

assign ci_4_fu_272_p2 = (ci_reg_139 + 5'd1);

assign co_10_fu_170_p2 = (co_reg_94 + 5'd1);

assign conv1_output_address0 = tmp_185_cast_fu_322_p1;

assign exitcond1_fu_240_p2 = ((w_reg_116 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond2_fu_211_p2 = ((h_reg_105 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond3_fu_164_p2 = ((co_reg_94 == 5'd24) ? 1'b1 : 1'b0);

assign exitcond_fu_266_p2 = ((ci_reg_139 == 5'd24) ? 1'b1 : 1'b0);

assign h_10_fu_217_p2 = (h_reg_105 + 6'd1);

assign notlhs_fu_344_p2 = ((tmp_16_fu_330_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs_fu_350_p2 = ((tmp_91_fu_340_p1 == 23'd0) ? 1'b1 : 1'b0);

assign p_shl1_cast_fu_201_p1 = tmp_116_fu_193_p3;

assign p_shl_cast_fu_189_p1 = tmp_s_fu_181_p3;

assign result_to_int_fu_327_p1 = result_reg_477;

assign tmp_116_fu_193_p3 = {{co_reg_94}, {3'd0}};

assign tmp_117_fu_205_p2 = (p_shl_cast_fu_189_p1 - p_shl1_cast_fu_201_p1);

assign tmp_118_fu_227_p2 = (tmp_cast_fu_223_p1 + p_shl_cast_reg_383);

assign tmp_119_fu_256_p2 = (tmp_177_cast_reg_411 + tmp_88_cast_fu_252_p1);

assign tmp_120_fu_282_p2 = (tmp_89_cast_fu_278_p1 + tmp_117_reg_388);

assign tmp_121_fu_292_p3 = {{ci_reg_139}, {5'd0}};

assign tmp_122_fu_304_p2 = (tmp_cast_reg_406 + tmp_181_cast_fu_300_p1);

assign tmp_123_fu_317_p2 = (tmp_88_cast_reg_424 + tmp_184_cast_fu_309_p3);

assign tmp_16_fu_330_p4 = {{result_to_int_fu_327_p1[30:23]}};

assign tmp_177_cast_fu_232_p3 = {{tmp_118_fu_227_p2}, {5'd0}};

assign tmp_178_cast_fu_261_p1 = tmp_119_fu_256_p2;

assign tmp_179_cast_fu_287_p1 = $signed(tmp_120_fu_282_p2);

assign tmp_181_cast_fu_300_p1 = tmp_121_fu_292_p3;

assign tmp_184_cast_fu_309_p3 = {{tmp_122_fu_304_p2}, {5'd0}};

assign tmp_185_cast_fu_322_p1 = tmp_123_fu_317_p2;

assign tmp_18_fu_356_p2 = (notrhs_fu_350_p2 | notlhs_fu_344_p2);

assign tmp_20_fu_362_p2 = (tmp_18_fu_356_p2 & tmp_19_reg_484);

assign tmp_88_cast_fu_252_p1 = w_reg_116;

assign tmp_89_cast_fu_278_p1 = ci_reg_139;

assign tmp_91_fu_340_p1 = result_to_int_fu_327_p1[22:0];

assign tmp_cast_fu_223_p1 = h_reg_105;

assign tmp_fu_176_p1 = co_reg_94;

assign tmp_s_fu_181_p3 = {{co_reg_94}, {5'd0}};

assign w_10_fu_246_p2 = (w_reg_116 + 6'd1);

assign weight_address0 = tmp_179_cast_fu_287_p1;

always @ (posedge ap_clk) begin
    p_shl_cast_reg_383[4:0] <= 5'b00000;
    p_shl_cast_reg_383[10] <= 1'b0;
    tmp_117_reg_388[2:0] <= 3'b000;
    tmp_cast_reg_406[10:6] <= 5'b00000;
    tmp_177_cast_reg_411[4:0] <= 5'b00000;
    tmp_88_cast_reg_424[15:6] <= 10'b0000000000;
end

endmodule //subconv_1x1_32
