// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "shuffle_48_p.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic shuffle_48_p::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic shuffle_48_p::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> shuffle_48_p::ap_ST_fsm_state1 = "1";
const sc_lv<7> shuffle_48_p::ap_ST_fsm_state2 = "10";
const sc_lv<7> shuffle_48_p::ap_ST_fsm_state3 = "100";
const sc_lv<7> shuffle_48_p::ap_ST_fsm_state4 = "1000";
const sc_lv<7> shuffle_48_p::ap_ST_fsm_state5 = "10000";
const sc_lv<7> shuffle_48_p::ap_ST_fsm_state6 = "100000";
const sc_lv<7> shuffle_48_p::ap_ST_fsm_state7 = "1000000";
const sc_lv<32> shuffle_48_p::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> shuffle_48_p::ap_const_lv32_1 = "1";
const sc_lv<1> shuffle_48_p::ap_const_lv1_0 = "0";
const sc_lv<32> shuffle_48_p::ap_const_lv32_2 = "10";
const sc_lv<32> shuffle_48_p::ap_const_lv32_3 = "11";
const sc_lv<32> shuffle_48_p::ap_const_lv32_4 = "100";
const sc_lv<32> shuffle_48_p::ap_const_lv32_5 = "101";
const sc_lv<7> shuffle_48_p::ap_const_lv7_0 = "0000000";
const sc_lv<1> shuffle_48_p::ap_const_lv1_1 = "1";
const sc_lv<4> shuffle_48_p::ap_const_lv4_0 = "0000";
const sc_lv<32> shuffle_48_p::ap_const_lv32_6 = "110";
const sc_lv<3> shuffle_48_p::ap_const_lv3_0 = "000";
const sc_lv<7> shuffle_48_p::ap_const_lv7_60 = "1100000";
const sc_lv<7> shuffle_48_p::ap_const_lv7_1 = "1";
const sc_lv<4> shuffle_48_p::ap_const_lv4_A = "1010";
const sc_lv<4> shuffle_48_p::ap_const_lv4_1 = "1";
const bool shuffle_48_p::ap_const_boolean_1 = true;

shuffle_48_p::shuffle_48_p(sc_module_name name) : sc_module(name), mVcdFile(0) {
    ShuffleNetV2_mux_fYi_x_U664 = new ShuffleNetV2_mux_fYi<1,1,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,6,8>("ShuffleNetV2_mux_fYi_x_U664");
    ShuffleNetV2_mux_fYi_x_U664->din1(buffer1_1_48_8x8_p_V_48_q0);
    ShuffleNetV2_mux_fYi_x_U664->din2(buffer1_1_48_8x8_p_V_1_q0);
    ShuffleNetV2_mux_fYi_x_U664->din3(buffer1_1_48_8x8_p_V_2_q0);
    ShuffleNetV2_mux_fYi_x_U664->din4(buffer1_1_48_8x8_p_V_3_q0);
    ShuffleNetV2_mux_fYi_x_U664->din5(buffer1_1_48_8x8_p_V_4_q0);
    ShuffleNetV2_mux_fYi_x_U664->din6(buffer1_1_48_8x8_p_V_5_q0);
    ShuffleNetV2_mux_fYi_x_U664->din7(buffer1_1_48_8x8_p_V_6_q0);
    ShuffleNetV2_mux_fYi_x_U664->din8(buffer1_1_48_8x8_p_V_7_q0);
    ShuffleNetV2_mux_fYi_x_U664->din9(buffer1_1_48_8x8_p_V_8_q0);
    ShuffleNetV2_mux_fYi_x_U664->din10(buffer1_1_48_8x8_p_V_9_q0);
    ShuffleNetV2_mux_fYi_x_U664->din11(buffer1_1_48_8x8_p_V_10_q0);
    ShuffleNetV2_mux_fYi_x_U664->din12(buffer1_1_48_8x8_p_V_11_q0);
    ShuffleNetV2_mux_fYi_x_U664->din13(buffer1_1_48_8x8_p_V_12_q0);
    ShuffleNetV2_mux_fYi_x_U664->din14(buffer1_1_48_8x8_p_V_13_q0);
    ShuffleNetV2_mux_fYi_x_U664->din15(buffer1_1_48_8x8_p_V_14_q0);
    ShuffleNetV2_mux_fYi_x_U664->din16(buffer1_1_48_8x8_p_V_15_q0);
    ShuffleNetV2_mux_fYi_x_U664->din17(buffer1_1_48_8x8_p_V_16_q0);
    ShuffleNetV2_mux_fYi_x_U664->din18(buffer1_1_48_8x8_p_V_17_q0);
    ShuffleNetV2_mux_fYi_x_U664->din19(buffer1_1_48_8x8_p_V_18_q0);
    ShuffleNetV2_mux_fYi_x_U664->din20(buffer1_1_48_8x8_p_V_19_q0);
    ShuffleNetV2_mux_fYi_x_U664->din21(buffer1_1_48_8x8_p_V_20_q0);
    ShuffleNetV2_mux_fYi_x_U664->din22(buffer1_1_48_8x8_p_V_21_q0);
    ShuffleNetV2_mux_fYi_x_U664->din23(buffer1_1_48_8x8_p_V_22_q0);
    ShuffleNetV2_mux_fYi_x_U664->din24(buffer1_1_48_8x8_p_V_23_q0);
    ShuffleNetV2_mux_fYi_x_U664->din25(buffer1_1_48_8x8_p_V_24_q0);
    ShuffleNetV2_mux_fYi_x_U664->din26(buffer1_1_48_8x8_p_V_25_q0);
    ShuffleNetV2_mux_fYi_x_U664->din27(buffer1_1_48_8x8_p_V_26_q0);
    ShuffleNetV2_mux_fYi_x_U664->din28(buffer1_1_48_8x8_p_V_27_q0);
    ShuffleNetV2_mux_fYi_x_U664->din29(buffer1_1_48_8x8_p_V_28_q0);
    ShuffleNetV2_mux_fYi_x_U664->din30(buffer1_1_48_8x8_p_V_29_q0);
    ShuffleNetV2_mux_fYi_x_U664->din31(buffer1_1_48_8x8_p_V_30_q0);
    ShuffleNetV2_mux_fYi_x_U664->din32(buffer1_1_48_8x8_p_V_31_q0);
    ShuffleNetV2_mux_fYi_x_U664->din33(buffer1_1_48_8x8_p_V_32_q0);
    ShuffleNetV2_mux_fYi_x_U664->din34(buffer1_1_48_8x8_p_V_33_q0);
    ShuffleNetV2_mux_fYi_x_U664->din35(buffer1_1_48_8x8_p_V_34_q0);
    ShuffleNetV2_mux_fYi_x_U664->din36(buffer1_1_48_8x8_p_V_35_q0);
    ShuffleNetV2_mux_fYi_x_U664->din37(buffer1_1_48_8x8_p_V_36_q0);
    ShuffleNetV2_mux_fYi_x_U664->din38(buffer1_1_48_8x8_p_V_37_q0);
    ShuffleNetV2_mux_fYi_x_U664->din39(buffer1_1_48_8x8_p_V_38_q0);
    ShuffleNetV2_mux_fYi_x_U664->din40(buffer1_1_48_8x8_p_V_39_q0);
    ShuffleNetV2_mux_fYi_x_U664->din41(buffer1_1_48_8x8_p_V_40_q0);
    ShuffleNetV2_mux_fYi_x_U664->din42(buffer1_1_48_8x8_p_V_41_q0);
    ShuffleNetV2_mux_fYi_x_U664->din43(buffer1_1_48_8x8_p_V_42_q0);
    ShuffleNetV2_mux_fYi_x_U664->din44(buffer1_1_48_8x8_p_V_43_q0);
    ShuffleNetV2_mux_fYi_x_U664->din45(buffer1_1_48_8x8_p_V_44_q0);
    ShuffleNetV2_mux_fYi_x_U664->din46(buffer1_1_48_8x8_p_V_45_q0);
    ShuffleNetV2_mux_fYi_x_U664->din47(buffer1_1_48_8x8_p_V_46_q0);
    ShuffleNetV2_mux_fYi_x_U664->din48(buffer1_1_48_8x8_p_V_47_q0);
    ShuffleNetV2_mux_fYi_x_U664->din49(p_lshr_f_cast_reg_1219);
    ShuffleNetV2_mux_fYi_x_U664->dout(tmp_fu_1101_p50);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_828_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_828_p2 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_10_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_10_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_11_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_11_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_12_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_12_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_13_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_13_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_14_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_14_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_15_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_15_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_16_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_16_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_17_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_17_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_18_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_18_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_19_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_19_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_1_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_1_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_20_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_20_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_21_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_21_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_22_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_22_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_23_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_23_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_24_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_24_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_25_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_25_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_26_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_26_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_27_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_27_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_28_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_28_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_29_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_29_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_2_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_2_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_30_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_30_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_31_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_31_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_32_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_32_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_33_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_33_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_34_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_34_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_35_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_35_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_36_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_36_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_37_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_37_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_38_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_38_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_39_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_39_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_3_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_3_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_40_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_40_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_41_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_41_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_42_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_42_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_43_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_43_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_44_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_44_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_45_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_45_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_46_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_46_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_47_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_47_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_48_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_48_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_4_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_4_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_5_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_5_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_6_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_6_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_7_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_7_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_8_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_8_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_9_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_486_cast_fu_1037_p1 );

    SC_METHOD(thread_buffer1_1_48_8x8_p_V_9_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_co_28_fu_834_p2);
    sensitive << ( co_reg_751 );

    SC_METHOD(thread_exitcond4_fu_988_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( h_reg_762 );

    SC_METHOD(thread_exitcond5_fu_828_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( co_reg_751 );

    SC_METHOD(thread_exitcond_fu_1089_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( w_reg_773 );

    SC_METHOD(thread_h_28_fu_994_p2);
    sensitive << ( h_reg_762 );

    SC_METHOD(thread_h_cast2_cast2_fu_880_p1);
    sensitive << ( h_reg_762 );

    SC_METHOD(thread_h_cast2_cast_fu_884_p1);
    sensitive << ( h_reg_762 );

    SC_METHOD(thread_left_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_484_cast_fu_1017_p1 );

    SC_METHOD(thread_left_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_output_V_address0);
    sensitive << ( output_V_addr_reg_1257 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_output_V_ce0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_output_V_d0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( storemerge_reg_784 );

    SC_METHOD(thread_output_V_we0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_p_lshr_f_cast_fu_840_p4);
    sensitive << ( co_reg_751 );

    SC_METHOD(thread_p_shl1_cast_fu_818_p1);
    sensitive << ( tmp_364_fu_810_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_858_p1);
    sensitive << ( tmp_366_fu_850_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_870_p1);
    sensitive << ( tmp_367_fu_862_p3 );

    SC_METHOD(thread_p_shl4_cast_fu_966_p1);
    sensitive << ( tmp_373_fu_958_p3 );

    SC_METHOD(thread_p_shl5_cast_fu_978_p1);
    sensitive << ( tmp_374_fu_970_p3 );

    SC_METHOD(thread_p_shl6_cast_fu_936_p1);
    sensitive << ( tmp_505_fu_928_p3 );

    SC_METHOD(thread_p_shl7_cast_fu_948_p1);
    sensitive << ( tmp_506_fu_940_p3 );

    SC_METHOD(thread_p_shl8_cast_fu_901_p1);
    sensitive << ( tmp_503_fu_893_p3 );

    SC_METHOD(thread_p_shl9_cast_fu_913_p1);
    sensitive << ( tmp_504_fu_905_p3 );

    SC_METHOD(thread_p_shl_cast_fu_806_p1);
    sensitive << ( tmp_s_fu_798_p3 );

    SC_METHOD(thread_tmp_364_fu_810_p3);
    sensitive << ( co_reg_751 );

    SC_METHOD(thread_tmp_365_fu_822_p2);
    sensitive << ( p_shl_cast_fu_806_p1 );
    sensitive << ( p_shl1_cast_fu_818_p1 );

    SC_METHOD(thread_tmp_366_fu_850_p3);
    sensitive << ( p_lshr_f_cast_fu_840_p4 );

    SC_METHOD(thread_tmp_367_fu_862_p3);
    sensitive << ( p_lshr_f_cast_fu_840_p4 );

    SC_METHOD(thread_tmp_368_fu_874_p2);
    sensitive << ( p_shl3_cast_fu_870_p1 );
    sensitive << ( p_shl2_cast_fu_858_p1 );

    SC_METHOD(thread_tmp_369_fu_888_p2);
    sensitive << ( tmp_368_reg_1224 );
    sensitive << ( h_cast2_cast_fu_884_p1 );

    SC_METHOD(thread_tmp_370_fu_917_p2);
    sensitive << ( p_shl8_cast_fu_901_p1 );
    sensitive << ( p_shl9_cast_fu_913_p1 );

    SC_METHOD(thread_tmp_371_fu_923_p2);
    sensitive << ( tmp_365_reg_1206 );
    sensitive << ( h_cast2_cast2_fu_880_p1 );

    SC_METHOD(thread_tmp_372_fu_952_p2);
    sensitive << ( p_shl6_cast_fu_936_p1 );
    sensitive << ( p_shl7_cast_fu_948_p1 );

    SC_METHOD(thread_tmp_373_fu_958_p3);
    sensitive << ( h_reg_762 );

    SC_METHOD(thread_tmp_374_fu_970_p3);
    sensitive << ( h_reg_762 );

    SC_METHOD(thread_tmp_375_fu_982_p2);
    sensitive << ( p_shl4_cast_fu_966_p1 );
    sensitive << ( p_shl5_cast_fu_978_p1 );

    SC_METHOD(thread_tmp_376_fu_1012_p2);
    sensitive << ( tmp_370_reg_1229 );
    sensitive << ( w_cast1_cast_fu_1008_p1 );

    SC_METHOD(thread_tmp_377_fu_1022_p2);
    sensitive << ( tmp_372_reg_1234 );
    sensitive << ( w_cast1_cast4_fu_1004_p1 );

    SC_METHOD(thread_tmp_378_fu_1032_p2);
    sensitive << ( tmp_375_reg_1239 );
    sensitive << ( w_cast1_cast3_fu_1000_p1 );

    SC_METHOD(thread_tmp_484_cast_fu_1017_p1);
    sensitive << ( tmp_376_fu_1012_p2 );

    SC_METHOD(thread_tmp_485_cast_fu_1027_p1);
    sensitive << ( tmp_377_fu_1022_p2 );

    SC_METHOD(thread_tmp_486_cast_fu_1037_p1);
    sensitive << ( tmp_378_fu_1032_p2 );

    SC_METHOD(thread_tmp_502_fu_794_p1);
    sensitive << ( co_reg_751 );

    SC_METHOD(thread_tmp_503_fu_893_p3);
    sensitive << ( tmp_369_fu_888_p2 );

    SC_METHOD(thread_tmp_504_fu_905_p3);
    sensitive << ( tmp_369_fu_888_p2 );

    SC_METHOD(thread_tmp_505_fu_928_p3);
    sensitive << ( tmp_371_fu_923_p2 );

    SC_METHOD(thread_tmp_506_fu_940_p3);
    sensitive << ( tmp_371_fu_923_p2 );

    SC_METHOD(thread_tmp_s_fu_798_p3);
    sensitive << ( co_reg_751 );

    SC_METHOD(thread_w_38_fu_1095_p2);
    sensitive << ( w_reg_773 );

    SC_METHOD(thread_w_cast1_cast3_fu_1000_p1);
    sensitive << ( w_reg_773 );

    SC_METHOD(thread_w_cast1_cast4_fu_1004_p1);
    sensitive << ( w_reg_773 );

    SC_METHOD(thread_w_cast1_cast_fu_1008_p1);
    sensitive << ( w_reg_773 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_502_reg_1202 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_828_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond4_fu_988_p2 );
    sensitive << ( exitcond_fu_1089_p2 );

    ap_CS_fsm = "0000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "shuffle_48_p_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, left_V_address0, "(port)left_V_address0");
    sc_trace(mVcdFile, left_V_ce0, "(port)left_V_ce0");
    sc_trace(mVcdFile, left_V_q0, "(port)left_V_q0");
    sc_trace(mVcdFile, output_V_address0, "(port)output_V_address0");
    sc_trace(mVcdFile, output_V_ce0, "(port)output_V_ce0");
    sc_trace(mVcdFile, output_V_we0, "(port)output_V_we0");
    sc_trace(mVcdFile, output_V_d0, "(port)output_V_d0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_48_address0, "(port)buffer1_1_48_8x8_p_V_48_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_48_ce0, "(port)buffer1_1_48_8x8_p_V_48_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_48_q0, "(port)buffer1_1_48_8x8_p_V_48_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_1_address0, "(port)buffer1_1_48_8x8_p_V_1_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_1_ce0, "(port)buffer1_1_48_8x8_p_V_1_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_1_q0, "(port)buffer1_1_48_8x8_p_V_1_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_2_address0, "(port)buffer1_1_48_8x8_p_V_2_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_2_ce0, "(port)buffer1_1_48_8x8_p_V_2_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_2_q0, "(port)buffer1_1_48_8x8_p_V_2_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_3_address0, "(port)buffer1_1_48_8x8_p_V_3_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_3_ce0, "(port)buffer1_1_48_8x8_p_V_3_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_3_q0, "(port)buffer1_1_48_8x8_p_V_3_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_4_address0, "(port)buffer1_1_48_8x8_p_V_4_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_4_ce0, "(port)buffer1_1_48_8x8_p_V_4_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_4_q0, "(port)buffer1_1_48_8x8_p_V_4_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_5_address0, "(port)buffer1_1_48_8x8_p_V_5_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_5_ce0, "(port)buffer1_1_48_8x8_p_V_5_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_5_q0, "(port)buffer1_1_48_8x8_p_V_5_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_6_address0, "(port)buffer1_1_48_8x8_p_V_6_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_6_ce0, "(port)buffer1_1_48_8x8_p_V_6_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_6_q0, "(port)buffer1_1_48_8x8_p_V_6_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_7_address0, "(port)buffer1_1_48_8x8_p_V_7_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_7_ce0, "(port)buffer1_1_48_8x8_p_V_7_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_7_q0, "(port)buffer1_1_48_8x8_p_V_7_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_8_address0, "(port)buffer1_1_48_8x8_p_V_8_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_8_ce0, "(port)buffer1_1_48_8x8_p_V_8_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_8_q0, "(port)buffer1_1_48_8x8_p_V_8_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_9_address0, "(port)buffer1_1_48_8x8_p_V_9_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_9_ce0, "(port)buffer1_1_48_8x8_p_V_9_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_9_q0, "(port)buffer1_1_48_8x8_p_V_9_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_10_address0, "(port)buffer1_1_48_8x8_p_V_10_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_10_ce0, "(port)buffer1_1_48_8x8_p_V_10_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_10_q0, "(port)buffer1_1_48_8x8_p_V_10_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_11_address0, "(port)buffer1_1_48_8x8_p_V_11_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_11_ce0, "(port)buffer1_1_48_8x8_p_V_11_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_11_q0, "(port)buffer1_1_48_8x8_p_V_11_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_12_address0, "(port)buffer1_1_48_8x8_p_V_12_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_12_ce0, "(port)buffer1_1_48_8x8_p_V_12_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_12_q0, "(port)buffer1_1_48_8x8_p_V_12_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_13_address0, "(port)buffer1_1_48_8x8_p_V_13_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_13_ce0, "(port)buffer1_1_48_8x8_p_V_13_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_13_q0, "(port)buffer1_1_48_8x8_p_V_13_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_14_address0, "(port)buffer1_1_48_8x8_p_V_14_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_14_ce0, "(port)buffer1_1_48_8x8_p_V_14_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_14_q0, "(port)buffer1_1_48_8x8_p_V_14_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_15_address0, "(port)buffer1_1_48_8x8_p_V_15_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_15_ce0, "(port)buffer1_1_48_8x8_p_V_15_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_15_q0, "(port)buffer1_1_48_8x8_p_V_15_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_16_address0, "(port)buffer1_1_48_8x8_p_V_16_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_16_ce0, "(port)buffer1_1_48_8x8_p_V_16_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_16_q0, "(port)buffer1_1_48_8x8_p_V_16_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_17_address0, "(port)buffer1_1_48_8x8_p_V_17_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_17_ce0, "(port)buffer1_1_48_8x8_p_V_17_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_17_q0, "(port)buffer1_1_48_8x8_p_V_17_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_18_address0, "(port)buffer1_1_48_8x8_p_V_18_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_18_ce0, "(port)buffer1_1_48_8x8_p_V_18_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_18_q0, "(port)buffer1_1_48_8x8_p_V_18_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_19_address0, "(port)buffer1_1_48_8x8_p_V_19_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_19_ce0, "(port)buffer1_1_48_8x8_p_V_19_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_19_q0, "(port)buffer1_1_48_8x8_p_V_19_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_20_address0, "(port)buffer1_1_48_8x8_p_V_20_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_20_ce0, "(port)buffer1_1_48_8x8_p_V_20_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_20_q0, "(port)buffer1_1_48_8x8_p_V_20_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_21_address0, "(port)buffer1_1_48_8x8_p_V_21_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_21_ce0, "(port)buffer1_1_48_8x8_p_V_21_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_21_q0, "(port)buffer1_1_48_8x8_p_V_21_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_22_address0, "(port)buffer1_1_48_8x8_p_V_22_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_22_ce0, "(port)buffer1_1_48_8x8_p_V_22_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_22_q0, "(port)buffer1_1_48_8x8_p_V_22_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_23_address0, "(port)buffer1_1_48_8x8_p_V_23_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_23_ce0, "(port)buffer1_1_48_8x8_p_V_23_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_23_q0, "(port)buffer1_1_48_8x8_p_V_23_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_24_address0, "(port)buffer1_1_48_8x8_p_V_24_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_24_ce0, "(port)buffer1_1_48_8x8_p_V_24_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_24_q0, "(port)buffer1_1_48_8x8_p_V_24_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_25_address0, "(port)buffer1_1_48_8x8_p_V_25_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_25_ce0, "(port)buffer1_1_48_8x8_p_V_25_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_25_q0, "(port)buffer1_1_48_8x8_p_V_25_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_26_address0, "(port)buffer1_1_48_8x8_p_V_26_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_26_ce0, "(port)buffer1_1_48_8x8_p_V_26_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_26_q0, "(port)buffer1_1_48_8x8_p_V_26_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_27_address0, "(port)buffer1_1_48_8x8_p_V_27_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_27_ce0, "(port)buffer1_1_48_8x8_p_V_27_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_27_q0, "(port)buffer1_1_48_8x8_p_V_27_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_28_address0, "(port)buffer1_1_48_8x8_p_V_28_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_28_ce0, "(port)buffer1_1_48_8x8_p_V_28_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_28_q0, "(port)buffer1_1_48_8x8_p_V_28_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_29_address0, "(port)buffer1_1_48_8x8_p_V_29_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_29_ce0, "(port)buffer1_1_48_8x8_p_V_29_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_29_q0, "(port)buffer1_1_48_8x8_p_V_29_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_30_address0, "(port)buffer1_1_48_8x8_p_V_30_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_30_ce0, "(port)buffer1_1_48_8x8_p_V_30_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_30_q0, "(port)buffer1_1_48_8x8_p_V_30_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_31_address0, "(port)buffer1_1_48_8x8_p_V_31_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_31_ce0, "(port)buffer1_1_48_8x8_p_V_31_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_31_q0, "(port)buffer1_1_48_8x8_p_V_31_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_32_address0, "(port)buffer1_1_48_8x8_p_V_32_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_32_ce0, "(port)buffer1_1_48_8x8_p_V_32_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_32_q0, "(port)buffer1_1_48_8x8_p_V_32_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_33_address0, "(port)buffer1_1_48_8x8_p_V_33_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_33_ce0, "(port)buffer1_1_48_8x8_p_V_33_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_33_q0, "(port)buffer1_1_48_8x8_p_V_33_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_34_address0, "(port)buffer1_1_48_8x8_p_V_34_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_34_ce0, "(port)buffer1_1_48_8x8_p_V_34_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_34_q0, "(port)buffer1_1_48_8x8_p_V_34_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_35_address0, "(port)buffer1_1_48_8x8_p_V_35_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_35_ce0, "(port)buffer1_1_48_8x8_p_V_35_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_35_q0, "(port)buffer1_1_48_8x8_p_V_35_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_36_address0, "(port)buffer1_1_48_8x8_p_V_36_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_36_ce0, "(port)buffer1_1_48_8x8_p_V_36_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_36_q0, "(port)buffer1_1_48_8x8_p_V_36_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_37_address0, "(port)buffer1_1_48_8x8_p_V_37_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_37_ce0, "(port)buffer1_1_48_8x8_p_V_37_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_37_q0, "(port)buffer1_1_48_8x8_p_V_37_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_38_address0, "(port)buffer1_1_48_8x8_p_V_38_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_38_ce0, "(port)buffer1_1_48_8x8_p_V_38_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_38_q0, "(port)buffer1_1_48_8x8_p_V_38_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_39_address0, "(port)buffer1_1_48_8x8_p_V_39_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_39_ce0, "(port)buffer1_1_48_8x8_p_V_39_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_39_q0, "(port)buffer1_1_48_8x8_p_V_39_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_40_address0, "(port)buffer1_1_48_8x8_p_V_40_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_40_ce0, "(port)buffer1_1_48_8x8_p_V_40_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_40_q0, "(port)buffer1_1_48_8x8_p_V_40_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_41_address0, "(port)buffer1_1_48_8x8_p_V_41_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_41_ce0, "(port)buffer1_1_48_8x8_p_V_41_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_41_q0, "(port)buffer1_1_48_8x8_p_V_41_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_42_address0, "(port)buffer1_1_48_8x8_p_V_42_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_42_ce0, "(port)buffer1_1_48_8x8_p_V_42_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_42_q0, "(port)buffer1_1_48_8x8_p_V_42_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_43_address0, "(port)buffer1_1_48_8x8_p_V_43_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_43_ce0, "(port)buffer1_1_48_8x8_p_V_43_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_43_q0, "(port)buffer1_1_48_8x8_p_V_43_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_44_address0, "(port)buffer1_1_48_8x8_p_V_44_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_44_ce0, "(port)buffer1_1_48_8x8_p_V_44_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_44_q0, "(port)buffer1_1_48_8x8_p_V_44_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_45_address0, "(port)buffer1_1_48_8x8_p_V_45_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_45_ce0, "(port)buffer1_1_48_8x8_p_V_45_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_45_q0, "(port)buffer1_1_48_8x8_p_V_45_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_46_address0, "(port)buffer1_1_48_8x8_p_V_46_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_46_ce0, "(port)buffer1_1_48_8x8_p_V_46_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_46_q0, "(port)buffer1_1_48_8x8_p_V_46_q0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_47_address0, "(port)buffer1_1_48_8x8_p_V_47_address0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_47_ce0, "(port)buffer1_1_48_8x8_p_V_47_ce0");
    sc_trace(mVcdFile, buffer1_1_48_8x8_p_V_47_q0, "(port)buffer1_1_48_8x8_p_V_47_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, tmp_502_fu_794_p1, "tmp_502_fu_794_p1");
    sc_trace(mVcdFile, tmp_502_reg_1202, "tmp_502_reg_1202");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_365_fu_822_p2, "tmp_365_fu_822_p2");
    sc_trace(mVcdFile, tmp_365_reg_1206, "tmp_365_reg_1206");
    sc_trace(mVcdFile, co_28_fu_834_p2, "co_28_fu_834_p2");
    sc_trace(mVcdFile, co_28_reg_1214, "co_28_reg_1214");
    sc_trace(mVcdFile, p_lshr_f_cast_fu_840_p4, "p_lshr_f_cast_fu_840_p4");
    sc_trace(mVcdFile, p_lshr_f_cast_reg_1219, "p_lshr_f_cast_reg_1219");
    sc_trace(mVcdFile, exitcond5_fu_828_p2, "exitcond5_fu_828_p2");
    sc_trace(mVcdFile, tmp_368_fu_874_p2, "tmp_368_fu_874_p2");
    sc_trace(mVcdFile, tmp_368_reg_1224, "tmp_368_reg_1224");
    sc_trace(mVcdFile, tmp_370_fu_917_p2, "tmp_370_fu_917_p2");
    sc_trace(mVcdFile, tmp_370_reg_1229, "tmp_370_reg_1229");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_372_fu_952_p2, "tmp_372_fu_952_p2");
    sc_trace(mVcdFile, tmp_372_reg_1234, "tmp_372_reg_1234");
    sc_trace(mVcdFile, tmp_375_fu_982_p2, "tmp_375_fu_982_p2");
    sc_trace(mVcdFile, tmp_375_reg_1239, "tmp_375_reg_1239");
    sc_trace(mVcdFile, h_28_fu_994_p2, "h_28_fu_994_p2");
    sc_trace(mVcdFile, h_28_reg_1247, "h_28_reg_1247");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, output_V_addr_reg_1257, "output_V_addr_reg_1257");
    sc_trace(mVcdFile, w_38_fu_1095_p2, "w_38_fu_1095_p2");
    sc_trace(mVcdFile, w_38_reg_1505, "w_38_reg_1505");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_fu_1101_p50, "tmp_fu_1101_p50");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, co_reg_751, "co_reg_751");
    sc_trace(mVcdFile, exitcond4_fu_988_p2, "exitcond4_fu_988_p2");
    sc_trace(mVcdFile, h_reg_762, "h_reg_762");
    sc_trace(mVcdFile, exitcond_fu_1089_p2, "exitcond_fu_1089_p2");
    sc_trace(mVcdFile, w_reg_773, "w_reg_773");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, storemerge_reg_784, "storemerge_reg_784");
    sc_trace(mVcdFile, tmp_484_cast_fu_1017_p1, "tmp_484_cast_fu_1017_p1");
    sc_trace(mVcdFile, tmp_485_cast_fu_1027_p1, "tmp_485_cast_fu_1027_p1");
    sc_trace(mVcdFile, tmp_486_cast_fu_1037_p1, "tmp_486_cast_fu_1037_p1");
    sc_trace(mVcdFile, tmp_s_fu_798_p3, "tmp_s_fu_798_p3");
    sc_trace(mVcdFile, tmp_364_fu_810_p3, "tmp_364_fu_810_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_806_p1, "p_shl_cast_fu_806_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_818_p1, "p_shl1_cast_fu_818_p1");
    sc_trace(mVcdFile, tmp_366_fu_850_p3, "tmp_366_fu_850_p3");
    sc_trace(mVcdFile, tmp_367_fu_862_p3, "tmp_367_fu_862_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_870_p1, "p_shl3_cast_fu_870_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_858_p1, "p_shl2_cast_fu_858_p1");
    sc_trace(mVcdFile, h_cast2_cast_fu_884_p1, "h_cast2_cast_fu_884_p1");
    sc_trace(mVcdFile, tmp_369_fu_888_p2, "tmp_369_fu_888_p2");
    sc_trace(mVcdFile, tmp_503_fu_893_p3, "tmp_503_fu_893_p3");
    sc_trace(mVcdFile, tmp_504_fu_905_p3, "tmp_504_fu_905_p3");
    sc_trace(mVcdFile, p_shl8_cast_fu_901_p1, "p_shl8_cast_fu_901_p1");
    sc_trace(mVcdFile, p_shl9_cast_fu_913_p1, "p_shl9_cast_fu_913_p1");
    sc_trace(mVcdFile, h_cast2_cast2_fu_880_p1, "h_cast2_cast2_fu_880_p1");
    sc_trace(mVcdFile, tmp_371_fu_923_p2, "tmp_371_fu_923_p2");
    sc_trace(mVcdFile, tmp_505_fu_928_p3, "tmp_505_fu_928_p3");
    sc_trace(mVcdFile, tmp_506_fu_940_p3, "tmp_506_fu_940_p3");
    sc_trace(mVcdFile, p_shl6_cast_fu_936_p1, "p_shl6_cast_fu_936_p1");
    sc_trace(mVcdFile, p_shl7_cast_fu_948_p1, "p_shl7_cast_fu_948_p1");
    sc_trace(mVcdFile, tmp_373_fu_958_p3, "tmp_373_fu_958_p3");
    sc_trace(mVcdFile, tmp_374_fu_970_p3, "tmp_374_fu_970_p3");
    sc_trace(mVcdFile, p_shl4_cast_fu_966_p1, "p_shl4_cast_fu_966_p1");
    sc_trace(mVcdFile, p_shl5_cast_fu_978_p1, "p_shl5_cast_fu_978_p1");
    sc_trace(mVcdFile, w_cast1_cast_fu_1008_p1, "w_cast1_cast_fu_1008_p1");
    sc_trace(mVcdFile, tmp_376_fu_1012_p2, "tmp_376_fu_1012_p2");
    sc_trace(mVcdFile, w_cast1_cast4_fu_1004_p1, "w_cast1_cast4_fu_1004_p1");
    sc_trace(mVcdFile, tmp_377_fu_1022_p2, "tmp_377_fu_1022_p2");
    sc_trace(mVcdFile, w_cast1_cast3_fu_1000_p1, "w_cast1_cast3_fu_1000_p1");
    sc_trace(mVcdFile, tmp_378_fu_1032_p2, "tmp_378_fu_1032_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

shuffle_48_p::~shuffle_48_p() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete ShuffleNetV2_mux_fYi_x_U664;
}

void shuffle_48_p::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond4_fu_988_p2.read(), ap_const_lv1_1))) {
        co_reg_751 = co_28_reg_1214.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        co_reg_751 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_1089_p2.read()))) {
        h_reg_762 = h_28_reg_1247.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond5_fu_828_p2.read(), ap_const_lv1_0))) {
        h_reg_762 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        storemerge_reg_784 = tmp_fu_1101_p50.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        storemerge_reg_784 = left_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_988_p2.read()))) {
        w_reg_773 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        w_reg_773 = w_38_reg_1505.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        co_28_reg_1214 = co_28_fu_834_p2.read();
        tmp_365_reg_1206 = tmp_365_fu_822_p2.read();
        tmp_502_reg_1202 = tmp_502_fu_794_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        h_28_reg_1247 = h_28_fu_994_p2.read();
        tmp_370_reg_1229 = tmp_370_fu_917_p2.read();
        tmp_372_reg_1234 = tmp_372_fu_952_p2.read();
        tmp_375_reg_1239 = tmp_375_fu_982_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        output_V_addr_reg_1257 =  (sc_lv<14>) (tmp_485_cast_fu_1027_p1.read());
        w_38_reg_1505 = w_38_fu_1095_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond5_fu_828_p2.read(), ap_const_lv1_0))) {
        p_lshr_f_cast_reg_1219 = co_reg_751.read().range(6, 1);
        tmp_368_reg_1224 = tmp_368_fu_874_p2.read();
    }
}

void shuffle_48_p::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void shuffle_48_p::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void shuffle_48_p::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void shuffle_48_p::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void shuffle_48_p::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void shuffle_48_p::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void shuffle_48_p::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void shuffle_48_p::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond5_fu_828_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_828_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_10_address0() {
    buffer1_1_48_8x8_p_V_10_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_10_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_10_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_10_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_11_address0() {
    buffer1_1_48_8x8_p_V_11_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_11_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_11_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_11_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_12_address0() {
    buffer1_1_48_8x8_p_V_12_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_12_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_12_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_12_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_13_address0() {
    buffer1_1_48_8x8_p_V_13_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_13_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_13_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_13_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_14_address0() {
    buffer1_1_48_8x8_p_V_14_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_14_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_14_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_14_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_15_address0() {
    buffer1_1_48_8x8_p_V_15_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_15_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_15_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_15_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_16_address0() {
    buffer1_1_48_8x8_p_V_16_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_16_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_16_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_16_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_17_address0() {
    buffer1_1_48_8x8_p_V_17_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_17_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_17_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_17_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_18_address0() {
    buffer1_1_48_8x8_p_V_18_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_18_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_18_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_18_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_19_address0() {
    buffer1_1_48_8x8_p_V_19_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_19_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_19_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_19_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_1_address0() {
    buffer1_1_48_8x8_p_V_1_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_1_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_1_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_20_address0() {
    buffer1_1_48_8x8_p_V_20_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_20_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_20_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_20_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_21_address0() {
    buffer1_1_48_8x8_p_V_21_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_21_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_21_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_21_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_22_address0() {
    buffer1_1_48_8x8_p_V_22_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_22_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_22_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_22_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_23_address0() {
    buffer1_1_48_8x8_p_V_23_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_23_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_23_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_23_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_24_address0() {
    buffer1_1_48_8x8_p_V_24_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_24_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_24_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_24_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_25_address0() {
    buffer1_1_48_8x8_p_V_25_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_25_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_25_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_25_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_26_address0() {
    buffer1_1_48_8x8_p_V_26_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_26_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_26_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_26_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_27_address0() {
    buffer1_1_48_8x8_p_V_27_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_27_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_27_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_27_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_28_address0() {
    buffer1_1_48_8x8_p_V_28_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_28_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_28_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_28_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_29_address0() {
    buffer1_1_48_8x8_p_V_29_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_29_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_29_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_29_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_2_address0() {
    buffer1_1_48_8x8_p_V_2_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_2_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_2_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_30_address0() {
    buffer1_1_48_8x8_p_V_30_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_30_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_30_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_30_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_31_address0() {
    buffer1_1_48_8x8_p_V_31_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_31_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_31_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_31_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_32_address0() {
    buffer1_1_48_8x8_p_V_32_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_32_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_32_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_32_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_33_address0() {
    buffer1_1_48_8x8_p_V_33_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_33_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_33_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_33_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_34_address0() {
    buffer1_1_48_8x8_p_V_34_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_34_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_34_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_34_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_35_address0() {
    buffer1_1_48_8x8_p_V_35_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_35_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_35_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_35_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_36_address0() {
    buffer1_1_48_8x8_p_V_36_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_36_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_36_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_36_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_37_address0() {
    buffer1_1_48_8x8_p_V_37_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_37_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_37_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_37_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_38_address0() {
    buffer1_1_48_8x8_p_V_38_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_38_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_38_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_38_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_39_address0() {
    buffer1_1_48_8x8_p_V_39_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_39_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_39_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_39_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_3_address0() {
    buffer1_1_48_8x8_p_V_3_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_3_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_3_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_40_address0() {
    buffer1_1_48_8x8_p_V_40_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_40_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_40_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_40_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_41_address0() {
    buffer1_1_48_8x8_p_V_41_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_41_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_41_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_41_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_42_address0() {
    buffer1_1_48_8x8_p_V_42_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_42_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_42_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_42_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_43_address0() {
    buffer1_1_48_8x8_p_V_43_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_43_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_43_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_43_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_44_address0() {
    buffer1_1_48_8x8_p_V_44_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_44_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_44_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_44_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_45_address0() {
    buffer1_1_48_8x8_p_V_45_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_45_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_45_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_45_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_46_address0() {
    buffer1_1_48_8x8_p_V_46_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_46_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_46_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_46_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_47_address0() {
    buffer1_1_48_8x8_p_V_47_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_47_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_47_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_47_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_48_address0() {
    buffer1_1_48_8x8_p_V_48_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_48_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_48_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_48_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_4_address0() {
    buffer1_1_48_8x8_p_V_4_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_4_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_4_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_4_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_5_address0() {
    buffer1_1_48_8x8_p_V_5_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_5_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_5_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_5_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_6_address0() {
    buffer1_1_48_8x8_p_V_6_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_6_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_6_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_6_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_7_address0() {
    buffer1_1_48_8x8_p_V_7_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_7_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_7_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_7_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_8_address0() {
    buffer1_1_48_8x8_p_V_8_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_8_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_8_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_8_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_9_address0() {
    buffer1_1_48_8x8_p_V_9_address0 =  (sc_lv<7>) (tmp_486_cast_fu_1037_p1.read());
}

void shuffle_48_p::thread_buffer1_1_48_8x8_p_V_9_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buffer1_1_48_8x8_p_V_9_ce0 = ap_const_logic_1;
    } else {
        buffer1_1_48_8x8_p_V_9_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_co_28_fu_834_p2() {
    co_28_fu_834_p2 = (!ap_const_lv7_1.is_01() || !co_reg_751.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_1) + sc_biguint<7>(co_reg_751.read()));
}

void shuffle_48_p::thread_exitcond4_fu_988_p2() {
    exitcond4_fu_988_p2 = (!h_reg_762.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(h_reg_762.read() == ap_const_lv4_A);
}

void shuffle_48_p::thread_exitcond5_fu_828_p2() {
    exitcond5_fu_828_p2 = (!co_reg_751.read().is_01() || !ap_const_lv7_60.is_01())? sc_lv<1>(): sc_lv<1>(co_reg_751.read() == ap_const_lv7_60);
}

void shuffle_48_p::thread_exitcond_fu_1089_p2() {
    exitcond_fu_1089_p2 = (!w_reg_773.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(w_reg_773.read() == ap_const_lv4_A);
}

void shuffle_48_p::thread_h_28_fu_994_p2() {
    h_28_fu_994_p2 = (!h_reg_762.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(h_reg_762.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void shuffle_48_p::thread_h_cast2_cast2_fu_880_p1() {
    h_cast2_cast2_fu_880_p1 = esl_zext<11,4>(h_reg_762.read());
}

void shuffle_48_p::thread_h_cast2_cast_fu_884_p1() {
    h_cast2_cast_fu_884_p1 = esl_zext<10,4>(h_reg_762.read());
}

void shuffle_48_p::thread_left_V_address0() {
    left_V_address0 =  (sc_lv<13>) (tmp_484_cast_fu_1017_p1.read());
}

void shuffle_48_p::thread_left_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        left_V_ce0 = ap_const_logic_1;
    } else {
        left_V_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_output_V_address0() {
    output_V_address0 = output_V_addr_reg_1257.read();
}

void shuffle_48_p::thread_output_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_ce0 = ap_const_logic_1;
    } else {
        output_V_ce0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_output_V_d0() {
    output_V_d0 = storemerge_reg_784.read();
}

void shuffle_48_p::thread_output_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_we0 = ap_const_logic_1;
    } else {
        output_V_we0 = ap_const_logic_0;
    }
}

void shuffle_48_p::thread_p_lshr_f_cast_fu_840_p4() {
    p_lshr_f_cast_fu_840_p4 = co_reg_751.read().range(6, 1);
}

void shuffle_48_p::thread_p_shl1_cast_fu_818_p1() {
    p_shl1_cast_fu_818_p1 = esl_zext<11,8>(tmp_364_fu_810_p3.read());
}

void shuffle_48_p::thread_p_shl2_cast_fu_858_p1() {
    p_shl2_cast_fu_858_p1 = esl_zext<10,9>(tmp_366_fu_850_p3.read());
}

void shuffle_48_p::thread_p_shl3_cast_fu_870_p1() {
    p_shl3_cast_fu_870_p1 = esl_zext<10,7>(tmp_367_fu_862_p3.read());
}

void shuffle_48_p::thread_p_shl4_cast_fu_966_p1() {
    p_shl4_cast_fu_966_p1 = esl_zext<8,7>(tmp_373_fu_958_p3.read());
}

void shuffle_48_p::thread_p_shl5_cast_fu_978_p1() {
    p_shl5_cast_fu_978_p1 = esl_zext<8,5>(tmp_374_fu_970_p3.read());
}

void shuffle_48_p::thread_p_shl6_cast_fu_936_p1() {
    p_shl6_cast_fu_936_p1 = esl_zext<15,14>(tmp_505_fu_928_p3.read());
}

void shuffle_48_p::thread_p_shl7_cast_fu_948_p1() {
    p_shl7_cast_fu_948_p1 = esl_zext<15,12>(tmp_506_fu_940_p3.read());
}

void shuffle_48_p::thread_p_shl8_cast_fu_901_p1() {
    p_shl8_cast_fu_901_p1 = esl_zext<14,13>(tmp_503_fu_893_p3.read());
}

void shuffle_48_p::thread_p_shl9_cast_fu_913_p1() {
    p_shl9_cast_fu_913_p1 = esl_zext<14,11>(tmp_504_fu_905_p3.read());
}

void shuffle_48_p::thread_p_shl_cast_fu_806_p1() {
    p_shl_cast_fu_806_p1 = esl_zext<11,10>(tmp_s_fu_798_p3.read());
}

void shuffle_48_p::thread_tmp_364_fu_810_p3() {
    tmp_364_fu_810_p3 = esl_concat<7,1>(co_reg_751.read(), ap_const_lv1_0);
}

void shuffle_48_p::thread_tmp_365_fu_822_p2() {
    tmp_365_fu_822_p2 = (!p_shl_cast_fu_806_p1.read().is_01() || !p_shl1_cast_fu_818_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl_cast_fu_806_p1.read()) + sc_biguint<11>(p_shl1_cast_fu_818_p1.read()));
}

void shuffle_48_p::thread_tmp_366_fu_850_p3() {
    tmp_366_fu_850_p3 = esl_concat<6,3>(p_lshr_f_cast_fu_840_p4.read(), ap_const_lv3_0);
}

void shuffle_48_p::thread_tmp_367_fu_862_p3() {
    tmp_367_fu_862_p3 = esl_concat<6,1>(p_lshr_f_cast_fu_840_p4.read(), ap_const_lv1_0);
}

void shuffle_48_p::thread_tmp_368_fu_874_p2() {
    tmp_368_fu_874_p2 = (!p_shl3_cast_fu_870_p1.read().is_01() || !p_shl2_cast_fu_858_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(p_shl3_cast_fu_870_p1.read()) + sc_biguint<10>(p_shl2_cast_fu_858_p1.read()));
}

void shuffle_48_p::thread_tmp_369_fu_888_p2() {
    tmp_369_fu_888_p2 = (!h_cast2_cast_fu_884_p1.read().is_01() || !tmp_368_reg_1224.read().is_01())? sc_lv<10>(): (sc_biguint<10>(h_cast2_cast_fu_884_p1.read()) + sc_biguint<10>(tmp_368_reg_1224.read()));
}

void shuffle_48_p::thread_tmp_370_fu_917_p2() {
    tmp_370_fu_917_p2 = (!p_shl8_cast_fu_901_p1.read().is_01() || !p_shl9_cast_fu_913_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(p_shl8_cast_fu_901_p1.read()) + sc_biguint<14>(p_shl9_cast_fu_913_p1.read()));
}

void shuffle_48_p::thread_tmp_371_fu_923_p2() {
    tmp_371_fu_923_p2 = (!h_cast2_cast2_fu_880_p1.read().is_01() || !tmp_365_reg_1206.read().is_01())? sc_lv<11>(): (sc_biguint<11>(h_cast2_cast2_fu_880_p1.read()) + sc_biguint<11>(tmp_365_reg_1206.read()));
}

void shuffle_48_p::thread_tmp_372_fu_952_p2() {
    tmp_372_fu_952_p2 = (!p_shl6_cast_fu_936_p1.read().is_01() || !p_shl7_cast_fu_948_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_shl6_cast_fu_936_p1.read()) + sc_biguint<15>(p_shl7_cast_fu_948_p1.read()));
}

void shuffle_48_p::thread_tmp_373_fu_958_p3() {
    tmp_373_fu_958_p3 = esl_concat<4,3>(h_reg_762.read(), ap_const_lv3_0);
}

void shuffle_48_p::thread_tmp_374_fu_970_p3() {
    tmp_374_fu_970_p3 = esl_concat<4,1>(h_reg_762.read(), ap_const_lv1_0);
}

void shuffle_48_p::thread_tmp_375_fu_982_p2() {
    tmp_375_fu_982_p2 = (!p_shl4_cast_fu_966_p1.read().is_01() || !p_shl5_cast_fu_978_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_shl4_cast_fu_966_p1.read()) + sc_biguint<8>(p_shl5_cast_fu_978_p1.read()));
}

void shuffle_48_p::thread_tmp_376_fu_1012_p2() {
    tmp_376_fu_1012_p2 = (!tmp_370_reg_1229.read().is_01() || !w_cast1_cast_fu_1008_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(tmp_370_reg_1229.read()) + sc_biguint<14>(w_cast1_cast_fu_1008_p1.read()));
}

void shuffle_48_p::thread_tmp_377_fu_1022_p2() {
    tmp_377_fu_1022_p2 = (!tmp_372_reg_1234.read().is_01() || !w_cast1_cast4_fu_1004_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_372_reg_1234.read()) + sc_biguint<15>(w_cast1_cast4_fu_1004_p1.read()));
}

void shuffle_48_p::thread_tmp_378_fu_1032_p2() {
    tmp_378_fu_1032_p2 = (!tmp_375_reg_1239.read().is_01() || !w_cast1_cast3_fu_1000_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_375_reg_1239.read()) + sc_biguint<8>(w_cast1_cast3_fu_1000_p1.read()));
}

void shuffle_48_p::thread_tmp_484_cast_fu_1017_p1() {
    tmp_484_cast_fu_1017_p1 = esl_zext<32,14>(tmp_376_fu_1012_p2.read());
}

void shuffle_48_p::thread_tmp_485_cast_fu_1027_p1() {
    tmp_485_cast_fu_1027_p1 = esl_zext<32,15>(tmp_377_fu_1022_p2.read());
}

void shuffle_48_p::thread_tmp_486_cast_fu_1037_p1() {
    tmp_486_cast_fu_1037_p1 = esl_zext<32,8>(tmp_378_fu_1032_p2.read());
}

void shuffle_48_p::thread_tmp_502_fu_794_p1() {
    tmp_502_fu_794_p1 = co_reg_751.read().range(1-1, 0);
}

void shuffle_48_p::thread_tmp_503_fu_893_p3() {
    tmp_503_fu_893_p3 = esl_concat<10,3>(tmp_369_fu_888_p2.read(), ap_const_lv3_0);
}

void shuffle_48_p::thread_tmp_504_fu_905_p3() {
    tmp_504_fu_905_p3 = esl_concat<10,1>(tmp_369_fu_888_p2.read(), ap_const_lv1_0);
}

void shuffle_48_p::thread_tmp_505_fu_928_p3() {
    tmp_505_fu_928_p3 = esl_concat<11,3>(tmp_371_fu_923_p2.read(), ap_const_lv3_0);
}

void shuffle_48_p::thread_tmp_506_fu_940_p3() {
    tmp_506_fu_940_p3 = esl_concat<11,1>(tmp_371_fu_923_p2.read(), ap_const_lv1_0);
}

void shuffle_48_p::thread_tmp_s_fu_798_p3() {
    tmp_s_fu_798_p3 = esl_concat<7,3>(co_reg_751.read(), ap_const_lv3_0);
}

void shuffle_48_p::thread_w_38_fu_1095_p2() {
    w_38_fu_1095_p2 = (!w_reg_773.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(w_reg_773.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void shuffle_48_p::thread_w_cast1_cast3_fu_1000_p1() {
    w_cast1_cast3_fu_1000_p1 = esl_zext<8,4>(w_reg_773.read());
}

void shuffle_48_p::thread_w_cast1_cast4_fu_1004_p1() {
    w_cast1_cast4_fu_1004_p1 = esl_zext<15,4>(w_reg_773.read());
}

void shuffle_48_p::thread_w_cast1_cast_fu_1008_p1() {
    w_cast1_cast_fu_1008_p1 = esl_zext<14,4>(w_reg_773.read());
}

void shuffle_48_p::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond5_fu_828_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond4_fu_988_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_1089_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_1089_p2.read()) && esl_seteq<1,1,1>(tmp_502_reg_1202.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm = "XXXXXXX";
            break;
    }
}

}

